### ISSUE TITLE
Many CLI errors when nodecore is syncing without connecting to nodecore

### ISSUE THREAD

**Issue by Hou5e** [VeriBlock/nodecore-releases#11]
It seems like nodecore-0.2.0 r4 takes a long time to load the blockchain on Windows, and the CLI has many errors after 30 minutes. This was from Windows on an attempt to restart nodecore, from running the startnodecore command.

After 30 minutes and 100MB of log files, I closed the nodecore loading when the CLI had errors (see below). This reproduced a second time after rebooting the PC (CLI errors after 30 minutes, and nodecore completed to the point where you could connect to it after 40 minutes and 140 MB of log files). After connecting the other normal commands would seem to hang the CLI, but would need a long time to complete (~4 minutes for getbalance).

I rebooted a different Ubuntu PC and this process took about 9 minutes (90MB of log files) and gave the proper response back allow me to connect to it.

The CLI window errors with this periodic repeating error message, every few minutes there would be a burst of ~20 of these:

Jul 14, 2018 1:18:59 AM io.grpc.internal.ManagedChannelImpl$ManagedChannelReference cleanQ
ueue
SEVERE: *~*~*~ Channel io.grpc.internal.ManagedChannelImpl-87 for target 127.0.0.1:10501 w
as not shutdown properly!!! ~*~*~*
    Make sure to call shutdown()/shutdownNow() and awaitTermination().
java.lang.RuntimeException: ManagedChannel allocation site
        at io.grpc.internal.ManagedChannelImpl$ManagedChannelReference.<init>(ManagedChann
elImpl.java:1185)
        at io.grpc.internal.ManagedChannelImpl.<init>(ManagedChannelImpl.java:504)
        at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannel
ImplBuilder.java:369)
        at nodecore.cli.services.AdminServiceClient.<init>(AdminServiceClient.java:63)
        at nodecore.cli.DefaultShell.connect(DefaultShell.java:70)
        at nodecore.cli.DefaultShell.access$100(DefaultShell.java:25)
        at nodecore.cli.DefaultShell$1.bound(DefaultShell.java:510)
        at nodecore.cli.DefaultShell$1.run(DefaultShell.java:479)
        at java.lang.Thread.run(Unknown Source)
.
.
.

Jul 14, 2018 1:26:51 AM io.grpc.internal.ManagedChannelImpl$ManagedChannelReference cleanQ
ueue
SEVERE: *~*~*~ Channel io.grpc.internal.ManagedChannelImpl-3214 for target 127.0.0.1:10501
 was not shutdown properly!!! ~*~*~*
    Make sure to call shutdown()/shutdownNow() and awaitTermination().
java.lang.RuntimeException: ManagedChannel allocation site
        at io.grpc.internal.ManagedChannelImpl$ManagedChannelReference.<init>(ManagedChann
elImpl.java:1185)
        at io.grpc.internal.ManagedChannelImpl.<init>(ManagedChannelImpl.java:504)
        at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannel
ImplBuilder.java:369)
        at nodecore.cli.services.AdminServiceClient.<init>(AdminServiceClient.java:63)
        at nodecore.cli.DefaultShell.connect(DefaultShell.java:70)
        at nodecore.cli.DefaultShell.access$100(DefaultShell.java:25)
        at nodecore.cli.DefaultShell$1.bound(DefaultShell.java:510)
        at nodecore.cli.DefaultShell$1.run(DefaultShell.java:479)
        at java.lang.Thread.run(Unknown Source)

**Comment by Hou5e** [comment]
This seems like you might just need to increase the timeout interval that triggers this.

This is still an issue in v0.2.9. If loading the blockchain takes a while before you get the message: 
```
A local NodeCore TestNet Instance is present on 127.0.0.1:10501!
To connect to NodeCore TestNet, type: connect 127.0.0.1:10501
```

It basically times-out after (30 minutes?) and you get hundreds of CLI errors:
```
...
Aug 06, 2018 8:59:28 AM io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference cleanQueue
SEVERE: *~*~*~ Channel ManagedChannelImpl{logId=8696, target=127.0.0.1:10501} was not shutdown properly!!! ~*~*~*
    Make sure to call shutdown()/shutdownNow() and wait until awaitTermination() returns true.
java.lang.RuntimeException: ManagedChannel allocation site
	at io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference.<init>(ManagedChannelOrphanWrapper.java:103)
	at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:53)
	at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:44)
	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:410)
	at nodecore.cli.services.AdminServiceClient.<init>(AdminServiceClient.java:63)
	at nodecore.cli.DefaultShell.connect(DefaultShell.java:70)
	at nodecore.cli.DefaultShell.access$100(DefaultShell.java:25)
	at nodecore.cli.DefaultShell$1.bound(DefaultShell.java:510)
	at nodecore.cli.DefaultShell$1.run(DefaultShell.java:479)
	at java.lang.Thread.run(Thread.java:748)

Aug 06, 2018 8:59:28 AM io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference cleanQueue
SEVERE: *~*~*~ Channel ManagedChannelImpl{logId=9068, target=127.0.0.1:10501} was not shutdown properly!!! ~*~*~*
    Make sure to call shutdown()/shutdownNow() and wait until awaitTermination() returns true.
java.lang.RuntimeException: ManagedChannel allocation site
	at io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference.<init>(ManagedChannelOrphanWrapper.java:103)
	at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:53)
	at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:44)
	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:410)
	at nodecore.cli.services.AdminServiceClient.<init>(AdminServiceClient.java:63)
	at nodecore.cli.DefaultShell.connect(DefaultShell.java:70)
	at nodecore.cli.DefaultShell.access$100(DefaultShell.java:25)
	at nodecore.cli.DefaultShell$1.bound(DefaultShell.java:510)
	at nodecore.cli.DefaultShell$1.run(DefaultShell.java:479)
	at java.lang.Thread.run(Thread.java:748)

Aug 06, 2018 8:59:28 AM io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference cleanQueue
SEVERE: *~*~*~ Channel ManagedChannelImpl{logId=8369, target=127.0.0.1:10501} was not shutdown properly!!! ~*~*~*
    Make sure to call shutdown()/shutdownNow() and wait until awaitTermination() returns true.
java.lang.RuntimeException: ManagedChannel allocation site
	at io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference.<init>(ManagedChannelOrphanWrapper.java:103)
	at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:53)
	at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:44)
	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:410)
	at nodecore.cli.services.AdminServiceClient.<init>(AdminServiceClient.java:63)
	at nodecore.cli.DefaultShell.connect(DefaultShell.java:70)
	at nodecore.cli.DefaultShell.access$100(DefaultShell.java:25)
	at nodecore.cli.DefaultShell$1.bound(DefaultShell.java:510)
	at nodecore.cli.DefaultShell$1.run(DefaultShell.java:479)
	at java.lang.Thread.run(Thread.java:748)



A local NodeCore TestNet Instance is present on 127.0.0.1:10501!
To connect to NodeCore TestNet, type: connect 127.0.0.1:10501

```

**Comment by Hou5e** [comment]
To reproduce this on Windows or Linux: Just start the CLI, and startnodecore, and wait 5-30 minutes for the error messages to start happening in the CLI (Don't connect to nodecore).
