### ISSUE TITLE
Many PoP operations failing with ArrayIndexOutOfBoundsException (nodecore-pop-0.2.0-r4)

### ISSUE THREAD

**Issue by a123b** [VeriBlock/nodecore-releases#12]
These operations immediatly fail upon resubmitting and stay in `listoperations` forever.  

Relevant section in log file:
```2018-07-14 15:21:34,454 ERROR [pool-44-thread-1] n.m.p.PoPMiningOperation [PoPMiningOperation.java:328] 3
java.lang.ArrayIndexOutOfBoundsException: 3
	at nodecore.miners.pop.common.MerkleLayer.getElement(MerkleLayer.java:65)
	at nodecore.miners.pop.common.BitcoinMerkleTree.getPathFromTxID(BitcoinMerkleTree.java:144)
	at nodecore.miners.pop.PoPMiningOperation.proveTransaction(PoPMiningOperation.java:324)
	at nodecore.miners.pop.PoPMiningOperation.lambda$wrapRunnable$1(PoPMiningOperation.java:247)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2018-07-14 15:21:34,455 ERROR [ForkJoinPool.commonPool-worker-1] n.m.p.s.DefaultShell [DefaultShell.java:123] Error proving transaction, see log for more detail. Operation can be resubmitted.
```
Full log file: [veriblock.nodecore-pop.log](https://github.com/VeriBlock/nodecore-releases/files/2194959/veriblock.nodecore-pop.log)

**Comment by a123b** [comment]
Hasn't happened again for quite a while now. Seems to be fixed.
