### ISSUE TITLE
Exception in thread "main" com.google.inject.ProvisionException: Unable to provision

### ISSUE THREAD

**Issue by denifednu** [VeriBlock/nodecore-releases#124]
Hi,
Newbie trying to start node for first time.  Not getting very far, please advise how to resolve the following:

[bc@bc nodecore-0.4.3]$ screen -S nodecore bin/nodecore
Copyright 2017-2019 Xenios SEZC
All rights reserved.
Distributed under the MIT software license, see the accompanying
file LICENSE or http://www.opensource.org/licenses/mit-license.php.

2019-04-18 23:41:59.555Z [main] INFO status-log - Program Version: VeriBlock NodeCore v0.4.3
2019-04-18 23:41:59.579Z [main] INFO status-log - Platform: Linux | 1.8.0_211
2019-04-18 23:41:59.583Z [main] INFO status-log - Available Processors: 2 | Max Memory: 5592576KB
2019-04-18 23:41:59.728Z [main] INFO status-log - {
  "user_language": "en",
  "java_runtime_name": "Java(TM) SE Runtime Environment",
  "sun_boot_library_path": "/home/bc/Downloads/java/jre1.8.0_211/lib/amd64",
  "java_runtime_version": "1.8.0_211-b12",
  "java_specification_version": "1.8",
  "os_name": "Linux",
  "os_arch": "amd64",
  "os_version": "5.0.6-200.fc29.x86_64",
  "memory_total_gb": "0.13 GB",
  "memory_max_gb": "5.33 GB",
  "processor_count": "2",
  "working_directory": "/home/bc/Downloads/veriblock-node/veriblock-nodecore-all-0.4.3/nodecore-0.4.3",
  "datetime_now_utc": "2019-04-18 23:41:59.592Z"
}
2019-04-18 23:41:59.856Z [main] INFO nodecore.h - NodeCore operating state is now: Started
2019-04-18 23:41:59.870Z [main] INFO nodecore.h - NodeCore network state is now: Disconnected
2019-04-18 23:41:59.881Z [main] INFO nodecore.h - NodeCore blockchain state is now: Initializing
2019-04-18 23:41:59.885Z [main] INFO nodecore.h - NodeCore operating state is now: Initializing
2019-04-18 23:42:00.772Z [main] INFO nodecore.d - Unable to load custom properties file: File 'nodecore.properties' does not exist. Using default properties.
2019-04-18 23:42:00.775Z [main] INFO nodecore.Program - Network: MainNet
Exception in thread "main" com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error injecting constructor, java.lang.NullPointerException
  at nodecore.a.e.<init>(DefaultBitcoinBlockchain.java:63)
  while locating nodecore.a.e
  at nodecore.e.configure(DefaultModule.java:62)
  while locating nodecore.b.g
    for the 3rd parameter of nodecore.c.a.r.<init>(DefaultBlockchain.java:155)
  while locating nodecore.c.a.r
  at nodecore.e.configure(DefaultModule.java:74)
  while locating nodecore.b.t

1 error
        at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1028)
        at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1054)
        at nodecore.Program.a(Program.java:92)
        at nodecore.Program.main(Program.java:174)
Caused by: java.lang.NullPointerException
        at nodecore.a.e.<init>(DefaultBitcoinBlockchain.java:68)
        at nodecore.a.e$$FastClassByGuice$$ad44af4b.newInstance(<generated>)
        at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:111)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
        at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:56)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:110)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
        at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:56)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
        at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1019)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085)
        at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1015)
        ... 3 more
2019-04-18 23:42:59.844Z [nc-monitor] INFO status-log - ** Minute Marker: 1 **
2019-04-18 23:42:59.849Z [nc-monitor] INFO status-log - Free Memory: 143673KB | MaxMemory: 5592576KB | TotalMemory: 183808KB
2019-04-18 23:42:59.851Z [nc-monitor] INFO status-log - Local Block: 0, Network Block: 0
2019-04-18 23:42:59.855Z [nc-monitor] INFO status-log - Total threads: 6
2019-04-18 23:43:59.846Z [nc-monitor] INFO status-log - ** Minute Marker: 2 **
2019-04-18 23:43:59.848Z [nc-monitor] INFO status-log - Free Memory: 143673KB | MaxMemory: 5592576KB | TotalMemory: 183808KB
2019-04-18 23:43:59.848Z [nc-monitor] INFO status-log - Local Block: 0, Network Block: 0
2019-04-18 23:43:59.850Z [nc-monitor] INFO status-log - Total threads: 6
2019-04-18 23:44:59.844Z [nc-monitor] INFO status-log - ** Minute Marker: 3 **
2019-04-18 23:44:59.845Z [nc-monitor] INFO status-log - Free Memory: 143673KB | MaxMemory: 5592576KB | TotalMemory: 183808KB
2019-04-18 23:44:59.846Z [nc-monitor] INFO status-log - Local Block: 0, Network Block: 0
2019-04-18 23:44:59.850Z [nc-monitor] INFO status-log - Total threads: 6
2019-04-18 23:45:59.844Z [nc-monitor] INFO status-log - ** Minute Marker: 4 **
2019-04-18 23:45:59.845Z [nc-monitor] INFO status-log - Free Memory: 143673KB | MaxMemory: 5592576KB | TotalMemory: 183808KB
2019-04-18 23:45:59.846Z [nc-monitor] INFO status-log - Local Block: 0, Network Block: 0
2019-04-18 23:45:59.847Z [nc-monitor] INFO status-log - Total threads: 6
2019-04-18 23:46:59.844Z [nc-monitor] INFO status-log - ** Minute Marker: 5 **
2019-04-18 23:46:59.846Z [nc-monitor] INFO status-log - Free Memory: 143673KB | MaxMemory: 5592576KB | TotalMemory: 183808KB
2019-04-18 23:46:59.846Z [nc-monitor] INFO status-log - Local Block: 0, Network Block: 0
2019-04-18 23:46:59.848Z [nc-monitor] INFO status-log - Total threads: 6

bootstrap file is downloaded/available and strace shows it does open the nodecore.dat file and create the other two files:
[bc@bc nodecore-0.4.3]$ ls -lh mainnet/
total 3.2G
-rw-r--r-- 1 bc bc 3.2G Apr 17 12:27 nodecore.dat
-rw-r--r-- 1 bc bc  32K Apr 18 23:42 nodecore.dat-shm
-rw-r--r-- 1 bc bc    0 Apr 18 23:32 nodecore.dat-wal

**Comment by denifednu** [comment]
bootstrap file is downloaded/available and strace shows it does open the nodecore.dat file and create the other two files:
[bc@bc nodecore-0.4.3]$ ls -lh mainnet/
total 3.2G
-rw-r--r-- 1 bc bc 3.2G Apr 17 12:27 nodecore.dat
-rw-r--r-- 1 bc bc  32K Apr 18 23:42 nodecore.dat-shm
-rw-r--r-- 1 bc bc    0 Apr 18 23:32 nodecore.dat-wal

**Comment by denifednu** [comment]
LuckyPool.IOToday at 1:40 AM
@denifednu your issue is nodecore.properties file is not existing. For old nodecore version it will generated but on 0.4.3 you need to copy it / create it

I created an empty nodecore.properties file in the current working directory, this solved the issue.
