### ISSUE TITLE
All PoP operations interrupted

### ISSUE THREAD

**Issue by protovist** [VeriBlock/nodecore-releases#17]
[veriblock.nodecore-pop.log](https://github.com/VeriBlock/nodecore-releases/files/2195380/veriblock.nodecore-pop.log)

**Comment by protovist** [comment]
I now have a state where resubmit fails immediately with this stack trace:

2018-07-16 21:03:58,369 INFO [main] n.m.p.s.DefaultCommandFactory [DefaultCommandFactory.java:61] USER COMMAND: res
ubmit fbbe01ae
2018-07-16 21:03:58,369 INFO [main] n.m.p.s.DefaultShell [DefaultShell.java:109] [V200] Success
2018-07-16 21:03:58,451 ERROR [miner] n.m.p.PoPMiningOperation [PoPMiningOperation.java:236] java.lang.NoClassDefFo
undError: javax/xml/bind/DatatypeConverter
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
        at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:205)
        at nodecore.miners.pop.PoPMiningOperation.doTask(PoPMiningOperation.java:231)
        at nodecore.miners.pop.PoPMiningOperation.run(PoPMiningOperation.java:82)
        at nodecore.miners.pop.PoPMiningOperation.resubmit(PoPMiningOperation.java:108)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at org.bitcoinj.utils.ContextPropagatingThreadFactory$1.run(ContextPropagatingThreadFactory.java:49)
        at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
        at nodecore.miners.pop.common.BitcoinMerkleTree.<init>(BitcoinMerkleTree.java:67)
        at nodecore.miners.pop.services.DefaultBitcoinService.calculateMerkleTree(DefaultBitcoinService.java:285)
        at nodecore.miners.pop.PoPMiningOperation.proveTransaction(PoPMiningOperation.java:323)
        at nodecore.miners.pop.PoPMiningOperation.lambda$wrapRunnable$1(PoPMiningOperation.java:247)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        ... 1 common frames omitted
2018-07-16 21:03:58,452 ERROR [ForkJoinPool.commonPool-worker-25] n.m.p.s.DefaultShell [DefaultShell.java:123] A ru
nning action was interrupted. Operation can be resubmitted.
