### ISSUE TITLE
"PoP mining operation is now: FAILED"

### ISSUE THREAD

**Issue by dumbcrypt0** [VeriBlock/nodecore-releases#20]
Shortly after running the "mine" command, the mining operation fails:

"Failed to get PoP publication information from Nodecore."

**Comment by Hou5e** [comment]
It seems line if nodecore is still syncing with the VeriBlock blockchain (the CLI 'getbalance' command doesn't show the full amount yet, and is catching up) you will get this error.

Blocking against PoP mining until everything is ready (especially with the PoP mining cron job setting enabled), and having the PoP miner indicate that status would probably be helpful.

This is some more PoP miner error log detail that might help with fixing this issue:
-----------------------------------------------------------------------------------
2018-07-15 13:17:54,908 INFO [NioClientManager] n.m.p.PoPMiningOperation [PoPMiningOperation.java:135] Restoring operation d8bbe167
2018-07-15 13:17:54,908 INFO [NioClientManager] n.m.p.PoPMiningOperation [PoPMiningOperation.java:170] [d8bbe167] Attempting to catch up with changes
2018-07-15 13:17:54,908 INFO [NioClientManager] n.m.p.PoPMiningOperation [PoPMiningOperation.java:176] [d8bbe167] Transaction Confidence: BUILDING
2018-07-15 13:17:54,908 INFO [NioClientManager] n.m.p.PoPMiningOperation [PoPMiningOperation.java:185] [d8bbe167] Found block 0000000064a270f5938b23277428d4f9524cd160f03e7b42f92818966c9f9650
2018-07-15 13:17:54,908 INFO [NioClientManager] n.m.p.PoPMiningOperation [PoPMiningOperation.java:135] Restoring operation 1f452ab1
2018-07-15 13:17:54,908 INFO [NioClientManager] n.m.p.PoPMiningOperation [PoPMiningOperation.java:170] [1f452ab1] Attempting to catch up with changes
2018-07-15 13:17:54,908 INFO [NioClientManager] n.m.p.PoPMiningOperation [PoPMiningOperation.java:176] [1f452ab1] Transaction Confidence: BUILDING
2018-07-15 13:17:54,908 INFO [NioClientManager] n.m.p.PoPMiningOperation [PoPMiningOperation.java:185] [1f452ab1] Found block 0000000064a270f5938b23277428d4f9524cd160f03e7b42f92818966c9f9650
2018-07-15 13:17:54,908 INFO [NioClientManager] n.m.p.PoPMiningOperation [PoPMiningOperation.java:135] Restoring operation 18fd6b5d
2018-07-15 13:17:54,908 INFO [NioClientManager] n.m.p.PoPMiningOperation [PoPMiningOperation.java:170] [18fd6b5d] Attempting to catch up with changes
2018-07-15 13:17:54,908 ERROR [NioClientManager] n.m.p.DefaultPoPMiner [DefaultPoPMiner.java:369] null
java.lang.NullPointerException: null
	at nodecore.miners.pop.PoPMiningOperation.fastForward(PoPMiningOperation.java:171)
	at nodecore.miners.pop.PoPMiningOperation.restore(PoPMiningOperation.java:166)
	at nodecore.miners.pop.DefaultPoPMiner.restoreOperations(DefaultPoPMiner.java:324)
	at nodecore.miners.pop.DefaultPoPMiner.addReadyCondition(DefaultPoPMiner.java:263)
	at nodecore.miners.pop.DefaultPoPMiner.onBitcoinServiceReady(DefaultPoPMiner.java:367)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:435)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at nodecore.miners.pop.InternalEventBus.post(InternalEventBus.java:28)
	at nodecore.miners.pop.services.DefaultBitcoinService$2.doneDownload(DefaultBitcoinService.java:121)
	at org.bitcoinj.core.listeners.DownloadProgressTracker.onBlocksDownloaded(DownloadProgressTracker.java:69)
	at org.bitcoinj.core.Peer$9.run(Peer.java:1169)
	at org.bitcoinj.utils.Threading$2.execute(Threading.java:141)
	at org.bitcoinj.core.Peer.invokeOnBlocksDownloaded(Peer.java:1166)
	at org.bitcoinj.core.Peer.endFilteredBlock(Peer.java:1102)
	at org.bitcoinj.core.Peer.processMessage(Peer.java:470)
	at org.bitcoinj.core.PeerSocketHandler.receiveBytes(PeerSocketHandler.java:184)
	at org.bitcoinj.net.ConnectionHandler.handleKey(ConnectionHandler.java:223)
	at org.bitcoinj.net.NioClientManager.handleKey(NioClientManager.java:86)
	at org.bitcoinj.net.NioClientManager.run(NioClientManager.java:122)
	at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:66)
	at com.google.common.util.concurrent.Callables$4.run(Callables.java:122)
	at org.bitcoinj.utils.ContextPropagatingThreadFactory$1.run(ContextPropagatingThreadFactory.java:49)
	at java.lang.Thread.run(Unknown Source)
2018-07-15 13:17:54,908 INFO [ForkJoinPool.commonPool-worker-9] n.m.p.s.DefaultShell [DefaultShell.java:127] Bitcoin service is ready
2018-07-15 13:17:54,924 INFO [ForkJoinPool.commonPool-worker-2] n.m.p.s.DefaultShell [DefaultShell.java:127] Blockchain downloading: 100%
2018-07-15 13:18:00,009 INFO [miner] n.m.p.s.DefaultShell [DefaultShell.java:251] [607bccd4] Mining operation current action: Ready
2018-07-15 13:18:00,009 INFO [miner] n.m.p.s.DefaultShell [DefaultShell.java:251] [607bccd4] Mining operation is now: RUNNING
2018-07-15 13:18:00,009 INFO [pool-13-thread-1] n.m.p.s.DefaultShell [DefaultShell.java:251] [607bccd4] Mining operation current action: Getting PoP publication data
2018-07-15 13:18:05,032 ERROR [pool-13-thread-1] n.m.p.PoPMiningOperation [PoPMiningOperation.java:264] Failed to get PoP publication data from NodeCore: Status{code=DEADLINE_EXCEEDED, description=deadline exceeded after 4999648517ns, cause=null}
2018-07-15 13:18:05,032 INFO [pool-13-thread-1] n.m.p.s.DefaultShell [DefaultShell.java:251] [607bccd4] Failed to get PoP publication data from NodeCore
2018-07-15 13:18:05,032 INFO [pool-13-thread-1] n.m.p.s.DefaultShell [DefaultShell.java:251] [607bccd4] Mining operation current action: Done
2018-07-15 13:18:05,032 INFO [pool-13-thread-1] n.m.p.s.DefaultShell [DefaultShell.java:251] [607bccd4] Mining operation is now: FAILED
2018-07-15 13:20:00,001 INFO [miner] n.m.p.s.DefaultShell [DefaultShell.java:251] [d8f7f519] Mining operation current action: Ready
2018-07-15 13:20:00,003 INFO [miner] n.m.p.s.DefaultShell [DefaultShell.java:251] [d8f7f519] Mining operation is now: RUNNING
2018-07-15 13:20:00,005 INFO [pool-14-thread-1] n.m.p.s.DefaultShell [DefaultShell.java:251] [d8f7f519] Mining operation current action: Getting PoP publication data
2018-07-15 13:20:05,009 ERROR [pool-14-thread-1] n.m.p.PoPMiningOperation [PoPMiningOperation.java:264] Failed to get PoP publication data from NodeCore: Status{code=DEADLINE_EXCEEDED, description=deadline exceeded after 4999640118ns, cause=null}
2018-07-15 13:20:05,010 INFO [pool-14-thread-1] n.m.p.s.DefaultShell [DefaultShell.java:251] [d8f7f519] Failed to get PoP publication data from NodeCore
2018-07-15 13:20:05,011 INFO [pool-14-thread-1] n.m.p.s.DefaultShell [DefaultShell.java:251] [d8f7f519] Mining operation current action: Done
2018-07-15 13:20:05,013 INFO [pool-14-thread-1] n.m.p.s.DefaultShell [DefaultShell.java:251] [d8f7f519] Mining operation is now: FAILED
