### ISSUE TITLE
ForkResolution Error Message

### ISSUE THREAD

**Issue by Hou5e** [VeriBlock/nodecore-releases#29]
This seems to happen pretty often in nodecore-0.2.0-r4:

ForkResolution Error Message (From: veriblock.nodecore.log):
===============
2018-07-15 14:58:11,843 ERROR [grpc-default-executor-350] n.core.a.n [ForkResolution.java:599] An exception was encountered while attempting to calculate relative PoP difficulties between chains 10999:00000000041B69EA294389A5C906D9D6BB5C56F717D1DCC4 and 10247:00000000088DC5375715559005F6468D32E7DEAF77052612 which diverged at 10247!
java.lang.IllegalArgumentException: A PoPContextChain was attempted to be constructed which contains keystones that don't reference each other: DDBB16789F15327ECC does not correspond with 00000000055A50E69A521B27A864CC8038A34C491FE3FE96!
	at nodecore.core.a.p.<init>(PoPContextChain.java:49)
	at nodecore.core.a.n.a(ForkResolution.java:211)
	at nodecore.core.a.n.a(ForkResolution.java:434)
	at nodecore.core.a.n.a(ForkResolution.java:241)
	at nodecore.core.a.k.a(DefaultBlockchain.java:1001)
	at nodecore.core.a.k.m(DefaultBlockchain.java:1549)
	at nodecore.core.a.k.a(DefaultBlockchain.java:1518)
	at nodecore.core.a.k.a(DefaultBlockchain.java:1348)
	at nodecore.core.a.k.a(DefaultBlockchain.java:1331)
	at nodecore.d.k.a(PeerEventListener.java:78)
	at sun.reflect.GeneratedMethodAccessor7.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:87)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:144)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:72)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:398)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:67)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:108)
	at com.google.common.eventbus.EventBus.post(EventBus.java:212)
	at nodecore.h.c.b(InternalEventBus.java:33)
	at nodecore.d.e.a(EventStreamObserver.java:49)
	at nodecore.d.e.onNext(EventStreamObserver.java:15)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onMessage(ClientCalls.java:406)
	at io.grpc.ForwardingClientCallListener.onMessage(ForwardingClientCallListener.java:36)
	at io.grpc.ForwardingClientCallListener.onMessage(ForwardingClientCallListener.java:36)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1MessagesAvailable.runInContext(ClientCallImpl.java:530)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

--
The corresponding error log message (From: veriblock.nodecore-error.log) says the same thing.

--
Logfile snip-its with more of the same error messages:
[ForkResolutionErrorMessages-veriblock.nodecore.log.txt](https://github.com/VeriBlock/nodecore-releases/files/2196174/ForkResolutionErrorMessages-veriblock.nodecore.log.txt)

[ForkResolutionErrorMessages-veriblock.nodecore-error.log.txt](https://github.com/VeriBlock/nodecore-releases/files/2196176/ForkResolutionErrorMessages-veriblock.nodecore-error.log.txt)

**Comment by Hou5e** [comment]
I haven't seen this message happen in current releases up to v0.2.9 so far, so closing this issue.
