### ISSUE TITLE
cannot initialize CPU miner - java IllegalArgumentException

### ISSUE THREAD

**Issue by gsxryan** [VeriBlock/nodecore-releases#4]
# Steps to reproduce

after properly funding wallet, starting popminer, execute 'startcpuminer'
Enter all info properly (final entry is wallet address)
```
18 
testnet-pool.veriblock.org:8500
V3BTUNk.....
```
Used copy/paste to enter address 

# Error
Either A
-The Application no longer responds (cursor blinking)
-CPU utilization has not increased

Or B:
```
Exception in thread "main" java.lang.IllegalArgumentException: parseClientCommand cannot be called with a null command line String!
        at nodecore.api.ucp.commands.UCPIncomingCommandParser.parseClientCommand(UCPIncomingCommandParser.java:85)
        at nodecore.miners.pow.MainClass.main(MainClass.java:126)
Application terminated unexpectedly, press any key to exit
```

**Comment by gsxryan** [comment]
Fixed by using port 8501.  

Instructions were unclear here;
https://wiki.veriblock.org/index.php?title=HowTo_run_and_connect_to_PoW_Miner_pool#Connect_to_an_Existing_Pool

Should reference, to: or include the 8501 detail in the above document.
https://wiki.veriblock.org/index.php?title=HowTo_run_PoW_CPU_Miner

**Comment by gsxryan** [comment]
Closing issue due to new feature. 

In the past we'd offer guidance and encourage installing a specific version, but the next major version of NodeCore will require Oracle Java 8. It will detect the Java version on startup, and if it's OpenJDK or Java 9/10, it will provide install links and gracefully exit.
It will save our community time to have NodeCore self-diagnose this upfront.

**Comment by gsxryan** [comment]
Wrong issue
