### ISSUE TITLE
[PoP Miner] constant ERROR: Mining operation action took longer than expected. Operation can be resubmitted.

### ISSUE THREAD

**Issue by gsxryan** [VeriBlock/nodecore-releases#45]
Constant repeating error messages with the bold text below.  Is it running 'mine' too often?  Or, Expected behavior?

```  
MINER: [494bc64a] Using miner address: ANON
  MINER: [494bc64a] Mining operation current action: Creating Bitcoin transaction containing PoP publication data
  **ERROR: Mining operation action took longer than expected. Operation can be resubmitted.**
  MINER: [c92ccbc7] Mining operation current action: Ready
  MINER: [c92ccbc7] Mining operation is now: RUNNING
```

**Comment by gsxryan** [comment]
Wiki suggests 
```
resubmit <id>
```
Resubmits an operation

Can this be automated, or scripted in the event this error appears?

**Comment by a123b** [comment]
This just happened to me, too. From the log file:
```
<Everything normal until here>
--------------
2018-07-19 06:45:03,557 INFO [NioClientManager] n.m.pop.i [PoPMiningOperation.java:520] [3b22d23d] New block added, checking confidence
2018-07-19 06:45:03,557 INFO [NioClientManager] n.m.pop.i [PoPMiningOperation.java:520] [2dabdf1d] New block added, checking confidence
2018-07-19 06:45:03,557 INFO [NioClientManager] n.m.pop.i [PoPMiningOperation.java:520] [ab4b8173] New block added, checking confidence
2018-07-19 06:45:11,048 ERROR [pool-286-thread-1] n.m.pop.i [PoPMiningOperation.java:328] null
java.lang.ArrayIndexOutOfBoundsException: null
2018-07-19 06:45:11,048 ERROR [ForkJoinPool.commonPool-worker-1] n.m.p.s.d [DefaultShell.java:123] Error proving transaction, see log for more detail. Operation can be resubmitted.
2018-07-19 06:45:11,049 ERROR [pool-284-thread-1] n.m.pop.i [PoPMiningOperation.java:328] null
java.lang.ArrayIndexOutOfBoundsException: null
2018-07-19 06:45:11,049 ERROR [ForkJoinPool.commonPool-worker-2] n.m.p.s.d [DefaultShell.java:123] Error proving transaction, see log for more detail. Operation can be resubmitted.
2018-07-19 06:45:11,049 ERROR [pool-282-thread-1] n.m.pop.i [PoPMiningOperation.java:328] null
java.lang.ArrayIndexOutOfBoundsException: null
2018-07-19 06:45:11,049 ERROR [pool-285-thread-1] n.m.pop.i [PoPMiningOperation.java:328] null
java.lang.ArrayIndexOutOfBoundsException: null
2018-07-19 06:45:11,049 ERROR [ForkJoinPool.commonPool-worker-1] n.m.p.s.d [DefaultShell.java:123] Error proving transaction, see log for more detail. Operation can be resubmitted.
2018-07-19 06:45:11,049 ERROR [ForkJoinPool.commonPool-worker-1] n.m.p.s.d [DefaultShell.java:123] Error proving transaction, see log for more detail. Operation can be resubmitted.
2018-07-19 06:45:11,049 ERROR [pool-283-thread-1] n.m.pop.i [PoPMiningOperation.java:328] null
java.lang.ArrayIndexOutOfBoundsException: null
2018-07-19 06:45:11,049 ERROR [ForkJoinPool.commonPool-worker-2] n.m.p.s.d [DefaultShell.java:123] Error proving transaction, see log for more detail. Operation can be resubmitted.
2018-07-19 06:45:15,270 INFO [main] n.m.p.s.c [DefaultCommandFactory.java:61] USER COMMAND: mine
2018-07-19 06:45:15,270 INFO [main] n.m.p.s.d [DefaultShell.java:109] [V201] Mining operation started
2018-07-19 06:45:15,270 INFO [miner] n.m.p.s.d [DefaultShell.java:251] [54f5490d] Mining operation current action: Ready
2018-07-19 06:45:15,270 INFO [miner] n.m.p.s.d [DefaultShell.java:251] [54f5490d] Mining operation is now: RUNNING
2018-07-19 06:45:15,270 INFO [pool-287-thread-1] n.m.p.s.d [DefaultShell.java:251] [54f5490d] Mining operation current action: Getting PoP publication data
2018-07-19 06:45:15,274 INFO [pool-287-thread-1] n.m.p.s.d [DefaultShell.java:251] [54f5490d] Received PoP mining instructions, securing block: 00000000077CCA9900B9EF8C5DE7D7503B45D65D1D685812
2018-07-19 06:45:15,274 INFO [pool-287-thread-1] n.m.p.s.d [DefaultShell.java:251] [54f5490d] Using miner address: VF87X8uwu82ygfiWWz1oqyGLrHWm2h
2018-07-19 06:45:15,275 INFO [pool-287-thread-1] n.m.p.s.d [DefaultShell.java:251] [54f5490d] Mining operation current action: Creating Bitcoin transaction containing PoP publication data
2018-07-19 06:45:15,275 INFO [pool-287-thread-1] n.m.p.d.c [DefaultBitcoinService.java:189] Found 8 UTXO
2018-07-19 06:45:19,240 INFO [ForkJoinPool.commonPool-worker-1] n.m.p.s.d [DefaultShell.java:127] Received pending tx 'd1dda7b130703341598430760f83ae3e3d00eff48eb340b6098c57907358f2fb', pending balance: '8.47990824 BTC'
2018-07-19 06:46:26,205 INFO [NioClientManager] n.m.pop.i [PoPMiningOperation.java:520] [d403b63b] New block added, checking confidence
2018-07-19 06:46:26,205 INFO [NioClientManager] n.m.pop.i [PoPMiningOperation.java:520] [b6aa3c07] New block added, checking confidence
2018-07-19 06:46:26,205 INFO [NioClientManager] n.m.pop.i [PoPMiningOperation.java:520] [3ff819ee] New block added, checking confidence

---- snip ---- (87 "New block added" messages removed)

2018-07-19 06:46:26,211 INFO [NioClientManager] n.m.pop.i [PoPMiningOperation.java:520] [3b22d23d] New block added, checking confidence
2018-07-19 06:46:26,211 INFO [NioClientManager] n.m.pop.i [PoPMiningOperation.java:520] [2dabdf1d] New block added, checking confidence
2018-07-19 06:46:26,211 INFO [NioClientManager] n.m.pop.i [PoPMiningOperation.java:520] [ab4b8173] New block added, checking confidence
2018-07-19 06:46:55,273 INFO [main] n.m.p.s.c [DefaultCommandFactory.java:61] USER COMMAND: mine
2018-07-19 06:46:55,273 INFO [main] n.m.p.s.d [DefaultShell.java:109] [V201] Mining operation started
2018-07-19 06:46:55,273 INFO [miner] n.m.p.s.d [DefaultShell.java:251] [a9b3e4aa] Mining operation current action: Ready
2018-07-19 06:46:55,274 INFO [miner] n.m.p.s.d [DefaultShell.java:251] [a9b3e4aa] Mining operation is now: RUNNING
2018-07-19 06:46:55,274 INFO [pool-288-thread-1] n.m.p.s.d [DefaultShell.java:251] [a9b3e4aa] Mining operation current action: Getting PoP publication data
2018-07-19 06:46:55,282 INFO [pool-288-thread-1] n.m.p.s.d [DefaultShell.java:251] [a9b3e4aa] Received PoP mining instructions, securing block: 000000000846D60A7BB489A9552C71613814E97CF543FBF2
2018-07-19 06:46:55,282 INFO [pool-288-thread-1] n.m.p.s.d [DefaultShell.java:251] [a9b3e4aa] Using miner address: VF87X8uwu82ygfiWWz1oqyGLrHWm2h
2018-07-19 06:46:55,282 INFO [pool-288-thread-1] n.m.p.s.d [DefaultShell.java:251] [a9b3e4aa] Mining operation current action: Creating Bitcoin transaction containing PoP publication data
2018-07-19 06:47:15,275 ERROR [miner] n.m.pop.i [PoPMiningOperation.java:233] Mining operation action took longer than expected
java.util.concurrent.TimeoutException: null
	at java.util.concurrent.FutureTask.get(FutureTask.java:205)
	at nodecore.miners.pop.i.a(PoPMiningOperation.java:231)
	at nodecore.miners.pop.i.c(PoPMiningOperation.java:78)
	at nodecore.miners.pop.e.c(DefaultPoPMiner.java:126)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.bitcoinj.utils.ContextPropagatingThreadFactory$1.run(ContextPropagatingThreadFactory.java:49)
	at java.lang.Thread.run(Thread.java:748)
2018-07-19 06:47:15,275 ERROR [ForkJoinPool.commonPool-worker-2] n.m.p.s.d [DefaultShell.java:123] Mining operation action took longer than expected. Operation can be resubmitted.
```
After the `ERROR java.lang.ArrayIndexOutOfBoundsException: null` message, every subsequent operation failed with the `Mining operation action took longer than expected` error message.

When I restarted the miner, I immediately encountered issue #5, don't know if it's related or just a coincidence. Only after deleting `bitcoin-pop-testnet.spvchain` did the miner work again.

**Comment by gsxryan** [comment]
Closing since new PoP instructions on Wiki seem to cover the issue.
