### ISSUE TITLE
PoP miner deadlock while receiving BTC

### ISSUE THREAD

**Issue by protovist** [VeriBlock/nodecore-releases#5]
Sending BTC to the PoP wallet while mining is in progress seems to be able to cause deadlock.

[nodecore-pop-deadlock.txt](https://github.com/VeriBlock/nodecore-releases/files/2193662/nodecore-pop-deadlock.txt)

**Comment by Hou5e** [comment]
This same thing also happened on Ubuntu with the POP miner v0.2.0-r4 for me (there might have been a slow network connection issue at that time?):
[bitcoinj.nodecore-pop.log](https://github.com/VeriBlock/nodecore-releases/files/2195135/bitcoinj.nodecore-pop.log)

 > Jul 14, 2018 12:24:04 AM com.google.common.util.concurrent.AbstractFuture executeListener
SEVERE: RuntimeException while executing runnable com.google.common.util.concurrent.Futures$4@766f9f40 with executor MoreExecutors.directExecutor()
com.google.common.util.concurrent.CycleDetectingLockFactory$PotentialDeadlockException: wallet -> peergroup, peergroup -> wallet
	at com.google.common.util.concurrent.CycleDetectingLockFactory$CycleDetectingReentrantLock.lock(CycleDetectingLockFactory.java:771)
	at org.bitcoinj.core.PeerGroup.getConnectedPeers(PeerGroup.java:952)
	at org.bitcoinj.core.PeerGroup.removePreMessageReceivedEventListener(PeerGroup.java:940)
	at org.bitcoinj.core.TransactionBroadcast$ConfidenceChange.onConfidenceChanged(TransactionBroadcast.java:207)
	at org.bitcoinj.core.TransactionConfidence$1.run(TransactionConfidence.java:456)
	at nodecore.miners.pop.Program.lambda$run$0(Program.java:52)
	at org.bitcoinj.core.TransactionConfidence.queueListeners(TransactionConfidence.java:453)
	at org.bitcoinj.wallet.Wallet.informConfidenceListenersIfNotReorganizing(Wallet.java:2085)
	at org.bitcoinj.wallet.Wallet.maybeCommitTx(Wallet.java:2474)
	at org.bitcoinj.wallet.Wallet.commitTx(Wallet.java:2494)
	at org.bitcoinj.wallet.Wallet.receivePending(Wallet.java:1707)
	at org.bitcoinj.wallet.Wallet.receivePending(Wallet.java:1751)
	at org.bitcoinj.core.PeerGroup$16.onSuccess(PeerGroup.java:2184)
	at org.bitcoinj.core.PeerGroup$16.onSuccess(PeerGroup.java:2170)
	at com.google.common.util.concurrent.Futures$4.run(Futures.java:1132)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:435)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:900)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:811)
	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:653)
	at com.google.common.util.concurrent.SettableFuture.set(SettableFuture.java:47)
	at org.bitcoinj.core.TransactionBroadcast$ConfidenceChange.onConfidenceChanged(TransactionBroadcast.java:209)
	at org.bitcoinj.core.TransactionConfidence$1.run(TransactionConfidence.java:456)
	at nodecore.miners.pop.Program.lambda$run$0(Program.java:52)
	at org.bitcoinj.core.TransactionConfidence.queueListeners(TransactionConfidence.java:453)
	at org.bitcoinj.core.TxConfidenceTable.seen(TxConfidenceTable.java:149)
	at org.bitcoinj.core.Peer.processInv(Peer.java:1224)
	at org.bitcoinj.core.Peer.processMessage(Peer.java:489)
	at org.bitcoinj.core.PeerSocketHandler.receiveBytes(PeerSocketHandler.java:184)
	at org.bitcoinj.net.ConnectionHandler.handleKey(ConnectionHandler.java:223)
	at org.bitcoinj.net.NioClientManager.handleKey(NioClientManager.java:86)
	at org.bitcoinj.net.NioClientManager.run(NioClientManager.java:122)
	at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:66)
	at com.google.common.util.concurrent.Callables$4.run(Callables.java:122)
	at org.bitcoinj.utils.ContextPropagatingThreadFactory$1.run(ContextPropagatingThreadFactory.java:49)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.google.common.util.concurrent.CycleDetectingLockFactory$ExampleStackTrace: peergroup -> wallet
	at com.google.common.util.concurrent.CycleDetectingLockFactory$CycleDetectingReentrantLock.lock(CycleDetectingLockFactory.java:771)
	at org.bitcoinj.wallet.Wallet.setTransactionBroadcaster(Wallet.java:5041)
	at org.bitcoinj.core.PeerGroup.addWallet(PeerGroup.java:1243)
	at org.bitcoinj.kits.WalletAppKit.startUp(WalletAppKit.java:324)
	at com.google.common.util.concurrent.AbstractIdleService$DelegateService$1.run(AbstractIdleService.java:62)
	at com.google.common.util.concurrent.Callables$4.run(Callables.java:122)
	... 1 more

**Comment by Hou5e** [comment]
This has happen a few times for me while receiving more Testnet BTC to the PoP wallet (I think especially when PoP mining transactions are in process). The PoP wallet funds "disappear" eventually, and most likely a new wallet address with no funds starts to be used (or, only the wallet transactions after the error are looked at for the balance, or it can't load the wallet at all), where you can't PoP mine anymore with 0 funds.

To fix this state, I had to run the 'resetwallet' command in the PoP miner, delete file 'bitcoin-pop-testnet.spvchain', and restart the PoP miner to reload the BTC transactions.
