### ISSUE TITLE
nodecore startup crashes without enough RAM. Needs more than 8GB

### ISSUE THREAD

**Issue by Hou5e** [VeriBlock/nodecore-releases#58]
Updating to nodecore-0.2.2, the startup sequence seems to hang processing the the existing blockchain data, and doesn't load nodes or do discovery of nodes, and eventually crashes.

**Deleting the blockchain and cache file seems to get it working again.**

After not getting a connection for a period of time (1-15 minutes), nodecore would error out with these errors (also note multiple minute marker numbers when it tries to catch up):
[nodecore-startup fails.txt](https://github.com/VeriBlock/nodecore-releases/files/2216495/nodecore-startup.fails.txt)

2018-07-21 01:48:27,395 INFO [pool-1-thread-1] n.Program [Program.java:49] ** Minute Marker: 5 **
2018-07-21 01:57:16,219 INFO [pool-1-thread-1] n.Program [Program.java:50] Free Memory: 383522KB | MaxMemory: 4818432KB | TotalMemory: 4818432KB
2018-07-21 01:59:39,532 INFO [pool-1-thread-1] n.Program [Program.java:49] ** Minute Marker: 16 **
2018-07-21 01:59:39,532 INFO [pool-1-thread-1] n.Program [Program.java:50] Free Memory: 383971KB | MaxMemory: 4818432KB | TotalMemory: 4818432KB
2018-07-21 01:59:39,533 INFO [pool-1-thread-1] n.Program [Program.java:49] ** Minute Marker: 16 **
2018-07-21 01:59:40,117 INFO [pool-1-thread-1] n.Program [Program.java:50] Free Memory: 384230KB | MaxMemory: 4818432KB | TotalMemory: 4818432KB
2018-07-21 01:59:40,117 INFO [pool-1-thread-1] n.Program [Program.java:49] ** Minute Marker: 16 **
2018-07-21 01:59:40,117 INFO [pool-1-thread-1] n.Program [Program.java:50] Free Memory: 383558KB | MaxMemory: 4818432KB | TotalMemory: 4818432KB
2018-07-21 01:59:40,723 INFO [pool-1-thread-1] n.Program [Program.java:49] ** Minute Marker: 16 **
2018-07-21 01:59:41,335 INFO [pool-1-thread-1] n.Program [Program.java:50] Free Memory: 383870KB | MaxMemory: 4818432KB | TotalMemory: 4818432KB
2018-07-21 01:59:41,336 INFO [pool-1-thread-1] n.Program [Program.java:49] ** Minute Marker: 16 **
2018-07-21 01:59:41,336 INFO [pool-1-thread-1] n.Program [Program.java:50] Free Memory: 383569KB | MaxMemory: 4818432KB | TotalMemory: 4818432KB
2018-07-21 01:59:41,966 INFO [pool-1-thread-1] n.Program [Program.java:49] ** Minute Marker: 16 **
2018-07-21 01:59:43,141 INFO [pool-1-thread-1] n.Program [Program.java:50] Free Memory: 383931KB | MaxMemory: 4818432KB | TotalMemory: 4818432KB
2018-07-21 01:59:47,285 INFO [pool-1-thread-1] n.Program [Program.java:49] ** Minute Marker: 16 **
2018-07-21 01:59:48,493 INFO [pool-1-thread-1] n.Program [Program.java:50] Free Memory: 383570KB | MaxMemory: 4818432KB | TotalMemory: 4818432KB
2018-07-21 01:59:51,434 INFO [pool-1-thread-1] n.Program [Program.java:49] ** Minute Marker: 16 **
2018-07-21 02:00:37,465 INFO [pool-1-thread-1] n.Program [Program.java:50] Free Memory: 387452KB | MaxMemory: 4818432KB | TotalMemory: 4818432KB
2018-07-21 02:00:37,465 INFO [pool-1-thread-1] n.Program [Program.java:49] ** Minute Marker: 17 **
2018-07-21 02:00:37,465 INFO [pool-1-thread-1] n.Program [Program.java:50] Free Memory: 387131KB | MaxMemory: 4818432KB | TotalMemory: 4818432KB
2018-07-21 02:00:37,466 INFO [pool-1-thread-1] n.Program [Program.java:49] ** Minute Marker: 17 **
2018-07-21 02:00:37,466 INFO [pool-1-thread-1] n.Program [Program.java:50] Free Memory: 387037KB | MaxMemory: 4818432KB | TotalMemory: 4818432KB
2018-07-21 02:00:37,466 INFO [pool-1-thread-1] n.Program [Program.java:49] ** Minute Marker: 17 **
2018-07-21 02:00:37,466 INFO [pool-1-thread-1] n.Program [Program.java:50] Free Memory: 386935KB | MaxMemory: 4818432KB | TotalMemory: 4818432KB
2018-07-21 02:00:37,466 INFO [pool-1-thread-1] n.Program [Program.java:49] ** Minute Marker: 17 **
2018-07-21 02:00:37,466 INFO [pool-1-thread-1] n.Program [Program.java:50] Free Memory: 386904KB | MaxMemory: 4818432KB | TotalMemory: 4818432KB
2018-07-21 02:01:12,545 INFO [pool-1-thread-1] n.Program [Program.java:49] ** Minute Marker: 18 **
2018-07-21 02:01:10,903 ERROR [ForkJoinPool.commonPool-worker-13] o.v.c.c.Crypto [Crypto.java:35] Unhandled exception
java.security.NoSuchAlgorithmException: Error constructing implementation (algorithm: SHA-256, provider: SUN, class: sun.security.provider.SHA2$SHA256)
	at java.security.Provider$Service.newInstance(Provider.java:1617)
	at sun.security.jca.GetInstance.getInstance(GetInstance.java:236)
	at sun.security.jca.GetInstance.getInstance(GetInstance.java:164)
	at java.security.Security.getImpl(Security.java:695)
	at java.security.MessageDigest.getInstance(MessageDigest.java:167)
	at org.veriblock.core.crypto.Crypto.<init>(Crypto.java:33)
	at org.veriblock.core.utilities.AddressUtility.isValidStandardAddress(AddressUtility.java:85)
	at nodecore.b.ap.<init>(TransactionAddress.java:31)
	at nodecore.core.transactions.DefaultTransaction.d(DefaultTransaction.java:441)
	at nodecore.core.transactions.DefaultTransaction.a(DefaultTransaction.java:389)
	at nodecore.core.transactions.DefaultTransaction.a(DefaultTransaction.java:366)
	at nodecore.core.transactions.DefaultTransaction.<init>(DefaultTransaction.java:320)
	at nodecore.core.transactions.DefaultTransaction$$FastClassByGuice$$f0b59614.newInstance(<generated>)
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:111)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1019)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1015)
	at com.google.inject.assistedinject.FactoryProvider2.invoke(FactoryProvider2.java:776)
	at com.sun.proxy.$Proxy17.a(Unknown Source)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at nodecore.core.a.i.<init>(DefaultBlock.java:391)
	at nodecore.core.a.i.<init>(DefaultBlock.java:374)
	at nodecore.core.a.i$$FastClassByGuice$$77582dfa.newInstance(<generated>)
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:111)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1019)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1015)
	at com.google.inject.assistedinject.FactoryProvider2.invoke(FactoryProvider2.java:776)
	at com.sun.proxy.$Proxy16.a(Unknown Source)
	at nodecore.core.a.k.a(DefaultBlockchain.java:203)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.Nodes$SizedCollectorTask.compute(Nodes.java:1878)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.OutOfMemoryError: Java heap space
	at sun.security.provider.SHA2.<init>(SHA2.java:82)
	at sun.security.provider.SHA2$SHA256.<init>(SHA2.java:260)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.security.Provider$Service.newInstance(Provider.java:1595)
	at sun.security.jca.GetInstance.getInstance(GetInstance.java:236)
	at sun.security.jca.GetInstance.getInstance(GetInstance.java:164)
	at java.security.Security.getImpl(Security.java:695)
	at java.security.MessageDigest.getInstance(MessageDigest.java:167)
	at org.veriblock.core.crypto.Crypto.<init>(Crypto.java:33)
	at org.veriblock.core.utilities.AddressUtility.isValidStandardAddress(AddressUtility.java:85)
	at nodecore.b.ap.<init>(TransactionAddress.java:31)
	at nodecore.core.transactions.DefaultTransaction.d(DefaultTransaction.java:441)
	at nodecore.core.transactions.DefaultTransaction.a(DefaultTransaction.java:389)
	at nodecore.core.transactions.DefaultTransaction.a(DefaultTransaction.java:366)
	at nodecore.core.transactions.DefaultTransaction.<init>(DefaultTransaction.java:320)
	at nodecore.core.transactions.DefaultTransaction$$FastClassByGuice$$f0b59614.newInstance(<generated>)
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:111)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1019)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1015)
	at com.google.inject.assistedinject.FactoryProvider2.invoke(FactoryProvider2.java:776)
	at com.sun.proxy.$Proxy17.a(Unknown Source)
	at nodecore.core.a.i$$Lambda$2/67671827.apply(Unknown Source)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)

**Comment by a123b** [comment]
> Caused by: java.lang.OutOfMemoryError: Java heap space

The problem is actually just that loading the blockchain needs an _insane_ amount of RAM. After setting `-Xmx10g`, the blockchain loaded just fine on my machine.
It seems like it requires almost 10x as much RAM as the save file, this really needs to be optimized!

**Comment by Hou5e** [comment]
Similar but slightly different issues happen in nodecore v0.2.9, where both 8GB and 12GB RAM linux PCs grind to halt, and hitting Crtl-C gives you an error with: **cause=java.lang.OutOfMemoryError: Java heap space**

On Windows with 32GB of RAM, Java is using 16GB of RAM.

I swapped some RAM around, so the 8GB PC now has 16GB, but that's probably not going to be enough to leave the current nodecore version running for weeks or months.

```
15:45:48.984 [grpc-default-executor-1481] INFO  nodecore.core.a.n - Duplicate PoP transaction found in a block trying to go onto the end of the longest chain!
15:45:39.588 [pool-1-thread-1] INFO  nodecore.Program - ** Minute Marker: 2363 **
15:45:48.984 [grpc-default-executor-1564] INFO  nodecore.f.b - Sending publication data back to PoP miner
15:45:48.984 [grpc-default-executor-1482] INFO  nodecore.d.k - Heartbeat received from 94.130.239.44
15:45:51.380 [grpc-default-executor-1512] WARN  nodecore.d.k - Event stream error from 198.204.235.122: Status{code=CANCELLED, description=Failed to read message., cause=java.lang.OutOfMemoryError: Java heap space
	at com.google.protobuf.AbstractMessageLite.toByteArray(AbstractMessageLite.java:70)
	at nodecore.core.a.k.k(DefaultBlock.java:696)
	at nodecore.core.a.n.c(DefaultBlockchain.java:367)
	at nodecore.core.a.n.a(DefaultBlockchain.java:1910)
	at nodecore.core.a.n.a(DefaultBlockchain.java:1736)
	at nodecore.core.a.n.a(DefaultBlockchain.java:1719)
	at nodecore.d.k.a(PeerEventListener.java:79)
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:87)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:144)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:72)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:398)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:67)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:108)
	at com.google.common.eventbus.EventBus.post(EventBus.java:212)
	at nodecore.h.c.b(InternalEventBus.java:33)
	at nodecore.d.e.a(EventStreamObserver.java:49)
	at nodecore.d.e.onNext(EventStreamObserver.java:15)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onMessage(ClientCalls.java:407)
	at io.grpc.ForwardingClientCallListener.onMessage(ForwardingClientCallListener.java:33)
	at io.grpc.ForwardingClientCallListener.onMessage(ForwardingClientCallListener.java:33)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1MessagesAvailable.runInContext(ClientCallImpl.java:519)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
}
15:45:55.502 [Thread-2] INFO  nodecore.h - NodeCore blockchain state is now: Paused
15:45:57.569 [pool-1-thread-1] INFO  nodecore.Program - Free Memory: 137533KB | MaxMemory: 7456768KB | TotalMemory: 7349760KB
15:45:57.569 [Thread-2] INFO  nodecore.h - NodeCore operating state is now: Terminating
15:45:57.569 [pool-1-thread-1] INFO  nodecore.Program - ** Minute Marker: 2364 **
```

**Comment by JoshRack** [comment]
No longer relevant
