### ISSUE TITLE
[PoP Miner] Bitcoin wallet corruption

### ISSUE THREAD

**Issue by a123b** [VeriBlock/nodecore-releases#72]
After sending a few transactions using `withdrawbitcointoaddress` and quitting using `quit`, my wallet got corrupted: When I try to start nodecore-pop I get this error message:
```
Exception in thread "main" java.lang.IllegalStateException: Expected the service  [FAILED] to be RUNNING, but the service has FAILED
        at com.google.common.util.concurrent.AbstractService.checkCurrentState(AbstractService.java:328)
        at com.google.common.util.concurrent.AbstractService.awaitRunning(AbstractService.java:266)
        at com.google.common.util.concurrent.AbstractIdleService.awaitRunning(AbstractIdleService.java:175)
        at nodecore.miners.pop.d.c.a(DefaultBitcoinService.java:151)
        at nodecore.miners.pop.e.run(DefaultPoPMiner.java:71)
        at nodecore.miners.pop.Program.a(Program.java:66)
        at nodecore.miners.pop.Program.main(Program.java:97)
Caused by: org.bitcoinj.wallet.UnreadableWalletException: Could not connect <<<edited out a transaction id>>> to <<<edited out another transaction id>>>
        at org.bitcoinj.wallet.WalletProtobufSerializer.connectTransactionOutputs(WalletProtobufSerializer.java:703)
        at org.bitcoinj.wallet.WalletProtobufSerializer.readWallet(WalletProtobufSerializer.java:508)
        at org.bitcoinj.wallet.WalletProtobufSerializer.readWallet(WalletProtobufSerializer.java:440)
        at org.bitcoinj.kits.WalletAppKit.loadWallet(WalletAppKit.java:402)
        at org.bitcoinj.kits.WalletAppKit.createOrLoadWallet(WalletAppKit.java:364)
        at org.bitcoinj.kits.WalletAppKit.startUp(WalletAppKit.java:273)
        at com.google.common.util.concurrent.AbstractIdleService$DelegateService$1.run(AbstractIdleService.java:62)
        at com.google.common.util.concurrent.Callables$4.run(Callables.java:122)
        at java.lang.Thread.run(Thread.java:748)
```
The wallet became unusable for me now. On testnet, it obviously isn't that big of a deal, but on the mainnet, this could have been disastrous.

Please implement the following features to mitigate corruptions like this:
- Add a possibility to clear and rebuild the transaction cache
- Wallet recovery using seed (the file contains 12 words, I assume it could be recovered with them)

**Comment by a123b** [comment]
This just happened to me again with another wallet. I split the request for recovery options into a separate issue #73 so that this issue is specifically about the cause of the corruption.
