### ISSUE TITLE
[PoP Miner] A problem occurred broadcasting the transaction to the peer group

### ISSUE THREAD

**Issue by a123b** [VeriBlock/nodecore-releases#76]
Over the last few days, I noticed many PoP operations failing with "A problem occurred broadcasting the transaction to the peer group".
The log files show two different reasons why the transaction are rejected:
- too-long-mempool-chain
```
2018-07-29 08:52:07,065 ERROR [NioClientManager] n.m.pop.i [PoPMiningOperation.java:320] A problem occurred broadcasting the transaction to the peer group
org.bitcoinj.core.RejectedTransactionException: Reject: tx 78fb802149b96d89db6b9b53bbd4d87da969af2f29c9f6f298e2c4ed6d597ea7 for reason 'too-long-mempool-chain' (64)
	at org.bitcoinj.core.TransactionBroadcast$2.onPreMessageReceived(TransactionBroadcast.java:102)
	at org.bitcoinj.core.Peer.processMessage(Peer.java:461)
	at org.bitcoinj.core.PeerSocketHandler.receiveBytes(PeerSocketHandler.java:184)
	at org.bitcoinj.net.ConnectionHandler.handleKey(ConnectionHandler.java:223)
	at org.bitcoinj.net.NioClientManager.handleKey(NioClientManager.java:86)
	at org.bitcoinj.net.NioClientManager.run(NioClientManager.java:122)
	at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:66)
	at com.google.common.util.concurrent.Callables$4.run(Callables.java:122)
	at org.bitcoinj.utils.ContextPropagatingThreadFactory$1.run(ContextPropagatingThreadFactory.java:49)
	at java.lang.Thread.run(Thread.java:748)
```
- txn-mempool-conflict
```
2018-07-30 09:14:56,608 ERROR [NioClientManager] n.m.pop.i [PoPMiningOperation.java:320] A problem occurred broadcasting the transaction to the peer group
org.bitcoinj.core.RejectedTransactionException: Reject: tx 82b34c0de837ac163caccbdeb69b15b1f683602f63f12e4e4a53b07aac02bdd5 for reason 'txn-mempool-conflict' (18)
	at org.bitcoinj.core.TransactionBroadcast$2.onPreMessageReceived(TransactionBroadcast.java:102)
	at org.bitcoinj.core.Peer.processMessage(Peer.java:461)
	at org.bitcoinj.core.PeerSocketHandler.receiveBytes(PeerSocketHandler.java:184)
	at org.bitcoinj.net.ConnectionHandler.handleKey(ConnectionHandler.java:223)
	at org.bitcoinj.net.NioClientManager.handleKey(NioClientManager.java:86)
	at org.bitcoinj.net.NioClientManager.run(NioClientManager.java:122)
	at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:66)
	at com.google.common.util.concurrent.Callables$4.run(Callables.java:122)
	at org.bitcoinj.utils.ContextPropagatingThreadFactory$1.run(ContextPropagatingThreadFactory.java:49)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by a123b** [comment]
The second error looks like a double spend attempt. I know I restarted the miner a few times around the time it happened. It seems like it doesn't save to the `pop.state` which UTXOs have pending transactions and doesn't check for it in the mempool, either.

**Comment by a123b** [comment]
It also happens if the miner is _not_ restarted. Maybe it happens if a transaction didn't get included in the Bitcoin block because the fee was too low, but the miner thinks it can reuse the UTXO even though it is still in the mempool?

**Comment by a123b** [comment]
Maybe this happens when a mine operation is started before the pending tx of the previous operation is received from a connected peer?
I found an interesting comment in the bitcoinj source:
https://github.com/bitcoinj/bitcoinj/blob/5df91ca8862bc3d871ed3c8c363f9b9fac793e1d/core/src/main/java/org/bitcoinj/wallet/Wallet.java#L3816-L3818
It looks like the miner directly uses `PeerGroup#broadcastTransaction()` to send the transaction, so `sendCoinsOffline()` is not called and the UTXOs are only marked as spent after the transaction is received back.
Maybe using `Wallet#sendCoins()` or manually calling `Wallet#sendCoinsOffline()` would fix the problem?

**Comment by a123b** [comment]
I noticed you can't use any `sendCoins()` method because you need to check the final fee before actually broadcasting the transaction.
But the only thing `sendCoinsOffline()` does that you're not already doing is to call `commitTx(request.tx)`.

I added this call right before `broadcastTransaction()` and it seems to actually fix the issue. The miner hasn't created a transaction causing `txn-mempool-conflict` since.

**Comment by JoshRack** [comment]
Thanks for the in-depth research on the bug! As you may have found digging through the bitcoinj source code, `commitTx` is what marks the UTXO as spent in the wallet. We chose to allow that to happen via `broadcastTransaction` as it's less likely to get the wallet into an inconsistent state which would require it to be unwound or reset.

The most common way I've seen the mempool conflict rejection is when you first run into a too-long-chain error. If you reach that point and continue to submit new transactions they all try to spend the last UTXO that was accepted by the peer group. Once all the pending transactions confirm, the too-long-chain ones are reprocessed, but since they're all now trying to spend the same UTXO, you get the mempool conflict error instead now.

I'll leave open as a potential for preventative measures.
