### ISSUE TITLE
[Nodecore 0.2.7] ERROR Unable to load blockchain

### ISSUE THREAD

**Issue by Hou5e** [VeriBlock/nodecore-releases#82]
Starting up nodecore has 2 errors and fails to load existing blockchain on Linux:

```
2018-07-30 22:29:29,931 INFO [main] n.core.a.m [DefaultBlockchain.java:2055] Ledger hash before unapplying block 40185: 7E1FC65C818679A9E6141263999F6B2B3240C61760077B67
2018-07-30 22:29:29,932 INFO [main] n.core.a.m [DefaultBlockchain.java:2057] Ledger hash after unapplying the block 40185: F788433B095C875FDF0FC6798D62BED37797C13F6B328190
2018-07-30 22:29:29,932 INFO [main] n.core.a.m [DefaultBlockchain.java:2054] Unapplying block: 40184 -> 000000000E55270A7B9B2BDC854C46F2EB4A59A061F57257
2018-07-30 22:29:29,932 INFO [main] n.core.a.m [DefaultBlockchain.java:2055] Ledger hash before unapplying block 40184: F788433B095C875FDF0FC6798D62BED37797C13F6B328190
2018-07-30 22:29:29,932 INFO [main] n.core.a.m [DefaultBlockchain.java:2057] Ledger hash after unapplying the block 40184: 7B65B12286E2C90CC4DCB79C134874B8B9640643E31A122D
2018-07-30 22:29:29,932 INFO [main] n.core.a.m [DefaultBlockchain.java:2054] Unapplying block: 40183 -> 000000001599883209DFD528180764E8B590DDCA242BE060
2018-07-30 22:29:29,932 INFO [main] n.core.a.m [DefaultBlockchain.java:2055] Ledger hash before unapplying block 40183: 7B65B12286E2C90CC4DCB79C134874B8B9640643E31A122D
2018-07-30 22:29:29,933 INFO [main] n.core.a.m [DefaultBlockchain.java:2057] Ledger hash after unapplying the block 40183: 2BC2F6363F9172723B2601C9DD2619B731AE0FDA60A2BE31
2018-07-30 22:29:29,933 INFO [main] n.core.a.m [DefaultBlockchain.java:2054] Unapplying block: 40182 -> 000000001038BFB0DEDDAB2CB7EA8AC1FA5D262D986DCE43
2018-07-30 22:29:29,933 INFO [main] n.core.a.m [DefaultBlockchain.java:2055] Ledger hash before unapplying block 40182: 2BC2F6363F9172723B2601C9DD2619B731AE0FDA60A2BE31
2018-07-30 22:29:29,944 INFO [main] n.core.a.m [DefaultBlockchain.java:2057] Ledger hash after unapplying the block 40182: CBF4D15DC1F4059A3BA5983B152144C3CC8BB54717047CD8
2018-07-30 22:29:29,944 INFO [main] n.core.a.m [DefaultBlockchain.java:2078] Applying block 0000000009C817F5A280BBEE621AB9C9760443294E67B6D0 @ 40182 from the new chain.
2018-07-30 22:29:29,944 INFO [main] n.core.a.m [DefaultBlockchain.java:2089] created validator...
2018-07-30 22:29:29,947 ERROR [main] n.core.a.m [DefaultBlockchain.java:2145] Exception while applying block from the best blockchain!
java.lang.NullPointerException: null
	at nodecore.core.a.j.c(DefaultBlock.java:475)
	at nodecore.core.a.g.g(BlockchainValidator.java:172)
	at nodecore.core.a.g.a(BlockchainValidator.java:40)
	at nodecore.core.a.m.c(DefaultBlockchain.java:2097)
	at nodecore.core.a.m.a(DefaultBlockchain.java:1941)
	at nodecore.core.a.m.h(DefaultBlockchain.java:197)
	at nodecore.Program.a(Program.java:89)
	at nodecore.Program.main(Program.java:161)
2018-07-30 22:29:29,947 INFO [main] n.core.a.m [DefaultBlockchain.java:2150] New blockchain needs to be reversed and original replayed
2018-07-30 22:29:29,949 INFO [main] n.core.a.m [DefaultBlockchain.java:660] applyBlock called...
2018-07-30 22:29:29,949 INFO [main] n.core.a.m [DefaultBlockchain.java:718] Done checking PoP endorsements for expected endorsed block hashes...
2018-07-30 22:29:29,950 INFO [main] n.core.a.m [DefaultBlockchain.java:732] All bitcoin headers added? true
2018-07-30 22:29:29,950 INFO [main] n.core.a.m [DefaultBlockchain.java:751] Doing PoP calcs...
2018-07-30 22:29:29,959 INFO [main] n.core.a.m [DefaultBlockchain.java:764] Got pop outputs
2018-07-30 22:29:29,959 INFO [main] n.core.a.m [DefaultBlockchain.java:777] Done filtering outputs...
2018-07-30 22:29:29,959 INFO [main] n.core.a.m [DefaultBlockchain.java:782] Done playing outputs...
2018-07-30 22:29:29,959 INFO [main] n.core.a.m [DefaultBlockchain.java:802] Done with pop stuff...
2018-07-30 22:29:29,959 INFO [main] n.core.a.m [DefaultBlockchain.java:817] total PoW outputs calculated
2018-07-30 22:29:29,959 INFO [main] n.core.a.m [DefaultBlockchain.java:841] Validated all PoW outputs...
2018-07-30 22:29:29,959 INFO [main] n.core.a.m [DefaultBlockchain.java:861] Checked all PoP outputs...
2018-07-30 22:29:29,970 INFO [main] n.core.a.m [DefaultBlockchain.java:883] Applied all transactions...
2018-07-30 22:29:29,970 INFO [main] n.core.a.m [DefaultBlockchain.java:903] Put best known Bitcoin blocks...
2018-07-30 22:29:29,970 INFO [main] n.core.a.m [DefaultBlockchain.java:909] Adjusted ledger for all PoW outputs...
2018-07-30 22:29:29,970 INFO [main] n.core.a.m [DefaultBlockchain.java:913] Done applying block 000000001038BFB0DEDDAB2CB7EA8AC1FA5D262D986DCE43!
```

```
2018-07-30 22:29:31,883 INFO [main] n.core.a.m [DefaultBlockchain.java:913] Done applying block 000000001124B8632C022B7497F053D7AC2C00573914244A!
2018-07-30 22:29:31,883 INFO [main] n.core.a.m [DefaultBlockchain.java:660] applyBlock called...
2018-07-30 22:29:31,883 INFO [main] n.core.a.m [DefaultBlockchain.java:718] Done checking PoP endorsements for expected endorsed block hashes...
2018-07-30 22:29:31,883 INFO [main] n.core.a.m [DefaultBlockchain.java:732] All bitcoin headers added? true
2018-07-30 22:29:31,883 INFO [main] n.core.a.m [DefaultBlockchain.java:751] Doing PoP calcs...
2018-07-30 22:29:31,883 INFO [main] n.core.a.m [DefaultBlockchain.java:764] Got pop outputs
2018-07-30 22:29:31,884 INFO [main] n.core.a.m [DefaultBlockchain.java:777] Done filtering outputs...
2018-07-30 22:29:31,884 INFO [main] n.core.a.m [DefaultBlockchain.java:782] Done playing outputs...
2018-07-30 22:29:31,884 INFO [main] n.core.a.m [DefaultBlockchain.java:802] Done with pop stuff...
2018-07-30 22:29:31,884 INFO [main] n.core.a.m [DefaultBlockchain.java:817] total PoW outputs calculated
2018-07-30 22:29:31,884 INFO [main] n.core.a.m [DefaultBlockchain.java:841] Validated all PoW outputs...
2018-07-30 22:29:31,884 INFO [main] n.core.a.m [DefaultBlockchain.java:861] Checked all PoP outputs...
2018-07-30 22:29:31,884 INFO [main] n.core.a.m [DefaultBlockchain.java:883] Applied all transactions...
2018-07-30 22:29:31,884 INFO [main] n.core.a.m [DefaultBlockchain.java:903] Put best known Bitcoin blocks...
2018-07-30 22:29:31,884 INFO [main] n.core.a.m [DefaultBlockchain.java:909] Adjusted ledger for all PoW outputs...
2018-07-30 22:29:31,884 INFO [main] n.core.a.m [DefaultBlockchain.java:913] Done applying block 000000001389C891918909DDBEF6080B9DA4BAEA8A771B2D!
2018-07-30 22:29:31,884 ERROR [main] n.Program [Program.java:91] Unable to load blockchain.
java.lang.IllegalStateException: a {THIS::TODO} can't be asked about the result of Fork Resolution before fork resolution has finished!
	at nodecore.core.a.h.c(ChainWalkBackAndReplayResult.java:31)
	at nodecore.core.a.m.a(DefaultBlockchain.java:1942)
	at nodecore.core.a.m.h(DefaultBlockchain.java:197)
	at nodecore.Program.a(Program.java:89)
	at nodecore.Program.main(Program.java:161)
```

**Comment by timstall** [comment]
@Hou5e with 0.2.9, is this still an issue?

**Comment by Hou5e** [comment]
No, I think this is fixed. The blockchain loaded past where it would stop before.
Please review the comments below before closing this:

1. There were hundreds of these messages at about that point in loading the blockchain:
```
2018-08-06 08:51:29,720 ERROR [main] n.core.a.n [DefaultBlockchain.java:2053] A forking point could not be found between our last known best blockchain (tip: 000000001389C891918909DDBEF6080B9DA4BAEA8A771B2D) @ 41499 and a better fork (tip: 000000000B9E88B66D56213F2A55D53B48628AA7FFA47D30) @ 41453! Is this a really old fork?
```
Error Logfile: [nodecore0.2.9-veriblock.nodecore-error.log](https://github.com/VeriBlock/nodecore-releases/files/2263517/nodecore0.2.9-veriblock.nodecore-error.log)

2. The attached log file has another error message when loading the blockchain. I created Issue #93 for it.

3. On the (1) Win7 and (2) Linux PCs, they all had Issue #11, and I updated that issue with some additional info.

**Comment by Hou5e** [comment]
Actually, one of the PCs stalled out loading the blockchain not long after the issue #93 happened. It wasn't doing much for the next ~3 hours, except rejecting current blocks, and it stopped asking for older needed blocks sequentially like it does when it started. Before that it was giving a lot of: N102: DOES_NOT_FIT messages.  The blockchain loading stopped in the 57K range out of 68k, after about 4 hour of trying to load the blockchain. So I stopped nodecore, and restarted it.

The second PC is now looking similar after 5 hours of trying to load the blockchain, with repeating messages like this:
```
13:04:50.784 [grpc-default-executor-269] INFO  nodecore.core.a.n - When adding block 63536
 (0000000000E4A07F7744836B356E39D911988D55222F9BF1), we are also adding 6 Bitcoin blocks.
13:04:50.789 [grpc-default-executor-269] INFO  nodecore.core.a.n - About to add block dire
ctly...
13:04:50.799 [grpc-default-executor-269] INFO  nodecore.core.a.n - Added block directly...
 state: DOES_NOT_FIT
13:04:50.809 [grpc-default-executor-269] INFO  nodecore.d.k - Rejected block 0000000000E4A
07F7744836B356E39D911988D55222F9BF1 @ 63536 for reason N102: DOES_NOT_FIT
13:04:55.369 [grpc-default-executor-269] INFO  nodecore.d.k - Add block 000000000214A16A2E
A05EFD4D37375B33DD4FD36A4CF4E2 @ 63537 received from 183.166.113.78
13:04:55.369 [grpc-default-executor-269] INFO  nodecore.core.a.n - Has not seen 0000000002
14A16A2EA05EFD4D37375B33DD4FD36A4CF4E2
13:04:55.954 [grpc-default-executor-269] INFO  nodecore.core.a.n - Added block 00000000021
4A16A2EA05EFD4D37375B33DD4FD36A4CF4E2 to broadcast history repo...
13:04:55.959 [grpc-default-executor-269] INFO  nodecore.core.a.n - Before adding block 635
37(000000000214A16A2EA05EFD4D37375B33DD4FD36A4CF4E2), latest Bitcoin block known: 00000000
000001EFBD20A73DB56BD32F1D5486D770C6E443C314D1E52AD23D80
13:04:55.969 [grpc-default-executor-269] INFO  nodecore.core.a.n - About to process block
cache...
13:04:55.979 [grpc-default-executor-269] INFO  nodecore.core.a.n - Done processing block c
ache...
13:04:55.989 [grpc-default-executor-269] INFO  nodecore.core.a.n - When adding block 63537
 (000000000214A16A2EA05EFD4D37375B33DD4FD36A4CF4E2), we are also adding 7 Bitcoin blocks.
13:04:55.994 [grpc-default-executor-269] INFO  nodecore.core.a.n - About to add block dire
ctly...
13:04:56.004 [grpc-default-executor-269] INFO  nodecore.core.a.n - Added block directly...
 state: DOES_NOT_FIT
13:04:56.014 [grpc-default-executor-269] INFO  nodecore.d.k - Rejected block 000000000214A
16A2EA05EFD4D37375B33DD4FD36A4CF4E2 @ 63537 for reason N102: DOES_NOT_FIT
13:05:00.739 [grpc-default-executor-269] INFO  nodecore.d.k - Add block 0000000000BF619D5C
F6C1E4EB34822BC809955BC990642A @ 63538 received from 183.166.113.78
13:05:00.744 [grpc-default-executor-269] INFO  nodecore.core.a.n - Has not seen 0000000000
BF619D5CF6C1E4EB34822BC809955BC990642A
13:05:00.764 [grpc-default-executor-270] INFO  nodecore.d.k - Sync request from block 6831
0 received from 69.197.128.74
13:05:01.319 [grpc-default-executor-269] INFO  nodecore.core.a.n - Added block 0000000000B
F619D5CF6C1E4EB34822BC809955BC990642A to broadcast history repo...
13:05:01.324 [grpc-default-executor-269] INFO  nodecore.core.a.n - Before adding block 635
38(0000000000BF619D5CF6C1E4EB34822BC809955BC990642A), latest Bitcoin block known: 00000000
000001EFBD20A73DB56BD32F1D5486D770C6E443C314D1E52AD23D80
13:05:01.339 [grpc-default-executor-269] INFO  nodecore.core.a.n - About to process block
cache...
13:05:01.344 [grpc-default-executor-269] INFO  nodecore.core.a.n - Done processing block c
ache...
13:05:01.354 [grpc-default-executor-269] INFO  nodecore.core.a.n - When adding block 63538
 (0000000000BF619D5CF6C1E4EB34822BC809955BC990642A), we are also adding 9 Bitcoin blocks.
13:05:01.364 [grpc-default-executor-269] INFO  nodecore.core.a.n - About to add block dire
ctly...
13:05:01.369 [grpc-default-executor-269] INFO  nodecore.core.a.n - Added block directly...
 state: DOES_NOT_FIT
13:05:01.374 [grpc-default-executor-269] INFO  nodecore.d.k - Rejected block 0000000000BF6
19D5CF6C1E4EB34822BC809955BC990642A @ 63538 for reason N102: DOES_NOT_FIT
13:05:01.374 [grpc-default-executor-275] INFO  nodecore.d.k - Sync request from block 6831
0 received from 80.211.187.51
13:05:01.374 [grpc-default-executor-274] INFO  nodecore.d.k - Sync request from block 6831
0 received from 88.99.249.217
13:05:01.379 [grpc-default-executor-273] INFO  nodecore.d.k - Sync request from block 6831
0 received from 94.130.239.42
13:05:01.379 [grpc-default-executor-272] INFO  nodecore.d.k - Sync request from block 6831
0 received from 35.237.197.48
13:05:01.379 [grpc-default-executor-271] INFO  nodecore.d.k - Sync request from block 6831
0 received from 18.191.139.75
13:05:06.579 [grpc-default-executor-271] INFO  nodecore.d.k - Add block 000000000007736EA5
820A2C1CB0E38DE9F7561AD01307D4 @ 63539 received from 183.166.113.78
13:05:06.589 [grpc-default-executor-271] INFO  nodecore.core.a.n - Has not seen 0000000000
07736EA5820A2C1CB0E38DE9F7561AD01307D4
13:05:07.174 [grpc-default-executor-271] INFO  nodecore.core.a.n - Added block 00000000000
7736EA5820A2C1CB0E38DE9F7561AD01307D4 to broadcast history repo...
13:05:07.179 [grpc-default-executor-271] INFO  nodecore.core.a.n - Before adding block 635
39(000000000007736EA5820A2C1CB0E38DE9F7561AD01307D4), latest Bitcoin block known: 00000000
000001EFBD20A73DB56BD32F1D5486D770C6E443C314D1E52AD23D80
13:05:07.189 [grpc-default-executor-271] INFO  nodecore.core.a.n - About to process block
cache...
13:05:07.199 [grpc-default-executor-271] INFO  nodecore.core.a.n - Done processing block c
ache...
13:05:07.204 [grpc-default-executor-271] INFO  nodecore.core.a.n - When adding block 63539
 (000000000007736EA5820A2C1CB0E38DE9F7561AD01307D4), we are also adding 9 Bitcoin blocks.
13:05:07.209 [grpc-default-executor-271] INFO  nodecore.core.a.n - About to add block dire
ctly...
13:05:07.219 [grpc-default-executor-271] INFO  nodecore.core.a.n - Added block directly...
 state: DOES_NOT_FIT
13:05:07.229 [grpc-default-executor-271] INFO  nodecore.d.k - Rejected block 0000000000077
36EA5820A2C1CB0E38DE9F7561AD01307D4 @ 63539 for reason N102: DOES_NOT_FIT
13:05:07.664 [pool-1-thread-1] INFO  nodecore.Program - ** Minute Marker: 285 **
13:05:07.664 [pool-1-thread-1] INFO  nodecore.Program - Free Memory: 696565KB | MaxMemory:
 7456768KB | TotalMemory: 2162688KB
13:05:09.819 [Thread-1] INFO  nodecore.d.c - periodicPrune finished, found 0 sync/reconcil
e jobs, and pruned 0
```
The 3rd PC loaded to the current block by about the 4th hour.
All 3 PCs started with existing blockchain, at about block 39K-41K.

**Comment by Hou5e** [comment]
Following up: One PC synced without any real issues. The other PCs synced with 1 or 2 restarts of nodecore to get to a good state. Issue #94 was what happened for the 2nd restart.

So, this can be closed now. The original issues didn't happen.
