### ISSUE TITLE
[PoP Miner] RuntimeExceptions when quitting

### ISSUE THREAD

**Issue by a123b** [VeriBlock/nodecore-releases#87]
I just tried to quit restart the PoP miner, but after I executed `quit`, it printed multiple instances of one of the two RuntimeException stack traces below and never actually exited, so I had to kill the process. This happend before saving the state to disk, so I ran into #84 immediately afterwards.

```
SEVERE: RuntimeException while executing runnable com.google.common.util.concurrent.Futures$4@624badf5 with executor MoreExecutors.directExecutor()
java.lang.IllegalArgumentException: missing event subscriber for an annotated method. Is nodecore.miners.pop.i@64c7438a registered?
        at com.google.common.eventbus.SubscriberRegistry.unregister(SubscriberRegistry.java:111)
        at com.google.common.eventbus.EventBus.unregister(EventBus.java:201)
        at nodecore.miners.pop.h.c(InternalEventBus.java:40)
        at nodecore.miners.pop.i.b(PoPMiningOperation.java:493)
        at nodecore.miners.pop.i.a(PoPMiningOperation.java:36)
        at nodecore.miners.pop.i$1.onFailure(PoPMiningOperation.java:322)
        at com.google.common.util.concurrent.Futures$4.run(Futures.java:1123)
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:435)
        at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:900)
        at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:811)
        at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:675)
        at com.google.common.util.concurrent.SettableFuture.setException(SettableFuture.java:53)
        at org.bitcoinj.core.TransactionBroadcast$2.onPreMessageReceived(TransactionBroadcast.java:102)
        at org.bitcoinj.core.Peer.processMessage(Peer.java:461)
        at org.bitcoinj.core.PeerSocketHandler.receiveBytes(PeerSocketHandler.java:184)
        at org.bitcoinj.net.ConnectionHandler.handleKey(ConnectionHandler.java:223)
        at org.bitcoinj.net.NioClientManager.handleKey(NioClientManager.java:86)
        at org.bitcoinj.net.NioClientManager.run(NioClientManager.java:122)
        at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:66)
        at com.google.common.util.concurrent.Callables$4.run(Callables.java:122)
        at org.bitcoinj.utils.ContextPropagatingThreadFactory$1.run(ContextPropagatingThreadFactory.java:49)
        at java.lang.Thread.run(Thread.java:748)
```

```
Exception in thread "main" java.lang.IllegalArgumentException: missing event subscriber for an annotated method. Is nodecore.miners.pop.i@7c892570 registered?
        at com.google.common.eventbus.SubscriberRegistry.unregister(SubscriberRegistry.java:111)
        at com.google.common.eventbus.EventBus.unregister(EventBus.java:201)
        at nodecore.miners.pop.h.c(InternalEventBus.java:40)
        at nodecore.miners.pop.i.d(PoPMiningOperation.java:100)
        at nodecore.miners.pop.e.m(DefaultPoPMiner.java:318)
        at nodecore.miners.pop.e.a(DefaultPoPMiner.java:89)
        at nodecore.miners.pop.Program.a(Program.java:74)
        at nodecore.miners.pop.Program.main(Program.java:97)
```

**Comment by JoshRack** [comment]
Much of this code, including when operations are saved, has been changed significantly since this was opened.
