### ISSUE TITLE
[PoP Miner] Rejected transaction for reason 'too-long-mempool-chain'

### ISSUE THREAD

**Issue by a123b** [VeriBlock/nodecore-releases#92]
Split from #76.

If you don't have many different UTXOs in your bitcoin-pop wallet, it can sometimes happen that transactions are rejected for reason 'too-long-mempool-chain' until the next BTC block is found:
```
2018-07-29 08:52:07,065 ERROR [NioClientManager] n.m.pop.i [PoPMiningOperation.java:320] A problem occurred broadcasting the transaction to the peer group
org.bitcoinj.core.RejectedTransactionException: Reject: tx 78fb802149b96d89db6b9b53bbd4d87da969af2f29c9f6f298e2c4ed6d597ea7 for reason 'too-long-mempool-chain' (64)
	at org.bitcoinj.core.TransactionBroadcast$2.onPreMessageReceived(TransactionBroadcast.java:102)
	at org.bitcoinj.core.Peer.processMessage(Peer.java:461)
	at org.bitcoinj.core.PeerSocketHandler.receiveBytes(PeerSocketHandler.java:184)
	at org.bitcoinj.net.ConnectionHandler.handleKey(ConnectionHandler.java:223)
	at org.bitcoinj.net.NioClientManager.handleKey(NioClientManager.java:86)
	at org.bitcoinj.net.NioClientManager.run(NioClientManager.java:122)
	at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:66)
	at com.google.common.util.concurrent.Callables$4.run(Callables.java:122)
	at org.bitcoinj.utils.ContextPropagatingThreadFactory$1.run(ContextPropagatingThreadFactory.java:49)
	at java.lang.Thread.run(Thread.java:748)
```

I think there can't really be done much other than printing a message suggesting the user to send multiple chunks of small balances to the wallet instead of one big balance.
The main problem seems to be that bitcoinj's `DefaultCoinSelector` doesn't prioritize pending UTXOs based on the unconfirmed chain length, so if one of them is significantly bigger than the others, its pending change will get selected for the next transaction, and eventually there will be a chain of unspent balances longer then the max allowed 25.

**Comment by JoshRack** [comment]
The DefaultCoinSelector in bitcoinj does sort by "coin age" for UTXO's. If you do get all UTXO's in your wallet into a pending state though, it would fall through to just sorting the hash values which is not guarantee of equal distribution.  At this point, we're only providing guidance documented via [https://wiki.veriblock.org](url)
