### ISSUE TITLE
[Nodecore v0.2.9] Event stream error - Invalid protobuf byte sequence

### ISSUE THREAD

**Issue by Hou5e** [VeriBlock/nodecore-releases#93]
This error seems to happen periodically while loading the blockchain with Nodecore v0.2.9. It doesn't look like it prevents anything from continuing (error messages from 2 different PCs):
```
2018-08-06 10:06:53,284 WARN [grpc-default-executor-38] n.d.k [PeerEventListener.java:101] Rejected transaction for reason: null
2018-08-06 10:06:54,488 INFO [grpc-default-executor-38] n.d.b.c [SyncJob.java:244] Downloaded block 58106 from 88.99.249.217
2018-08-06 10:06:54,488 INFO [grpc-default-executor-38] n.d.b.c [SyncJob.java:244] Downloaded block 58107 from 88.99.249.217
2018-08-06 10:06:54,492 WARN [grpc-default-executor-38] n.d.k [PeerEventListener.java:101] Rejected transaction for reason: null
2018-08-06 10:06:54,497 WARN [grpc-default-executor-38] n.d.k [PeerEventListener.java:101] Rejected transaction for reason: null
2018-08-06 10:06:54,501 WARN [grpc-default-executor-38] n.d.k [PeerEventListener.java:101] Rejected transaction for reason: null
2018-08-06 10:06:55,198 INFO [grpc-default-executor-38] n.d.k [PeerEventListener.java:74] Add block 000000000065D9234F8993CA4FE28EA4E0F43ECF60167F79 @ 57382 received from 80.211.187.51
2018-08-06 10:06:55,318 WARN [grpc-default-executor-38] n.d.k [PeerEventListener.java:382] Event stream error from 88.99.249.217: Status{code=CANCELLED, description=Failed to read message., cause=io.grpc.StatusRuntimeException: INTERNAL: Invalid protobuf byte sequence
	at io.grpc.Status.asRuntimeException(Status.java:517)
	at io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller.parse(ProtoLiteUtils.java:218)
	at io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller.parse(ProtoLiteUtils.java:118)
	at io.grpc.MethodDescriptor.parseResponse(MethodDescriptor.java:266)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1MessagesAvailable.runInContext(ClientCallImpl.java:519)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.google.protobuf.InvalidProtocolBufferException: Protocol message had invalid UTF-8.
	at com.google.protobuf.InvalidProtocolBufferException.invalidUtf8(InvalidProtocolBufferException.java:148)
	at com.google.protobuf.CodedInputStream$ArrayDecoder.readStringRequireUtf8(CodedInputStream.java:830)
	at nodecore.api.grpc.VeriBlockMessages$Transaction.<init>(VeriBlockMessages.java:12993)
	at nodecore.api.grpc.VeriBlockMessages$Transaction.<init>(VeriBlockMessages.java:12885)
	at nodecore.api.grpc.VeriBlockMessages$Transaction$1.parsePartialFrom(VeriBlockMessages.java:14962)
	at nodecore.api.grpc.VeriBlockMessages$Transaction$1.parsePartialFrom(VeriBlockMessages.java:14957)
	at com.google.protobuf.CodedInputStream$ArrayDecoder.readMessage(CodedInputStream.java:911)
	at nodecore.api.grpc.VeriBlockMessages$SignedTransaction.<init>(VeriBlockMessages.java:2536)
	at nodecore.api.grpc.VeriBlockMessages$SignedTransaction.<init>(VeriBlockMessages.java:2477)
	at nodecore.api.grpc.VeriBlockMessages$SignedTransaction$1.parsePartialFrom(VeriBlockMessages.java:3179)
	at nodecore.api.grpc.VeriBlockMessages$SignedTransaction$1.parsePartialFrom(VeriBlockMessages.java:3174)
	at com.google.protobuf.CodedInputStream$ArrayDecoder.readMessage(CodedInputStream.java:911)
	at nodecore.api.grpc.VeriBlockMessages$TransactionUnion.<init>(VeriBlockMessages.java:15073)
	at nodecore.api.grpc.VeriBlockMessages$TransactionUnion.<init>(VeriBlockMessages.java:15017)
	at nodecore.api.grpc.VeriBlockMessages$TransactionUnion$1.parsePartialFrom(VeriBlockMessages.java:16001)
	at nodecore.api.grpc.VeriBlockMessages$TransactionUnion$1.parsePartialFrom(VeriBlockMessages.java:15996)
	at com.google.protobuf.CodedInputStream$ArrayDecoder.readMessage(CodedInputStream.java:911)
	at nodecore.api.grpc.VeriBlockMessages$Block.<init>(VeriBlockMessages.java:27186)
	at nodecore.api.grpc.VeriBlockMessages$Block.<init>(VeriBlockMessages.java:27078)
	at nodecore.api.grpc.VeriBlockMessages$Block$1.parsePartialFrom(VeriBlockMessages.java:29261)
	at nodecore.api.grpc.VeriBlockMessages$Block$1.parsePartialFrom(VeriBlockMessages.java:29256)
	at com.google.protobuf.CodedInputStream$ArrayDecoder.readMessage(CodedInputStream.java:911)
	at nodecore.api.grpc.VeriBlockMessages$Event.<init>(VeriBlockMessages.java:46636)
	at nodecore.api.grpc.VeriBlockMessages$Event.<init>(VeriBlockMessages.java:46592)
	at nodecore.api.grpc.VeriBlockMessages$Event$1.parsePartialFrom(VeriBlockMessages.java:49106)
	at nodecore.api.grpc.VeriBlockMessages$Event$1.parsePartialFrom(VeriBlockMessages.java:49101)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:91)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:49)
	at io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller.parseFrom(ProtoLiteUtils.java:223)
	at io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller.parse(ProtoLiteUtils.java:215)
	... 8 more
}
2018-08-06 10:06:55,319 INFO [grpc-default-executor-38] n.d.b.c [SyncJob.java:187] Aborting sync with peer 88.99.249.217
2018-08-06 10:06:55,319 INFO [grpc-default-executor-38] n.d.b.c [SyncJob.java:195] Job 84f3f4c3-1573-4e19-8614-ad11707ca334 has been canceled.
2018-08-06 10:06:55,319 INFO [grpc-default-executor-38] nodecore.h [NodeCoreState.java:76] NodeCore blockchain state is now: Stale
2018-08-06 10:06:55,319 ERROR [pool-28-thread-1] n.d.b.c [SyncJob.java:142] null
java.lang.InterruptedException: null
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedNanos(AbstractQueuedSynchronizer.java:1039)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1328)
	at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:277)
	at nodecore.d.b.c.g(SyncJob.java:129)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2018-08-06 10:06:55,319 INFO [grpc-default-executor-38] n.d.c [DefaultPeerHub.java:223] Job 84f3f4c3-1573-4e19-8614-ad11707ca334 completed, there are now 0 reconcile/sync jobs running
2018-08-06 10:06:58,319 INFO [pool-4-thread-1] n.d.i [Peer.java:125] Opening connection to 88.99.249.217
2018-08-06 10:06:58,320 INFO [pool-1-thread-1] n.Program [Program.java:54] ** Minute Marker: 78 **
2018-08-06 10:06:58,320 INFO [pool-1-thread-1] n.Program [Program.java:55] Free Memory: 2282643KB | MaxMemory: 7456768KB | TotalMemory: 4668928KB
2018-08-06 10:06:58,875 INFO [grpc-default-executor-38] n.d.m [PeerTable.java:272] Added peer 88.99.249.217
2018-08-06 10:06:58,875 INFO [grpc-default-executor-38] n.d.k [PeerEventListener.java:106] Announce received from 88.99.249.217
2018-08-06 10:06:59,266 INFO [grpc-default-executor-38] n.d.k [PeerEventListener.java:74] Add block 00000000020A07A556E1E1F9F507F9C56AF51926BB339A59 @ 57383 received from 80.211.187.51
2018-08-06 10:07:00,767 INFO [grpc-default-executor-38] n.d.k [PeerEventListener.java:129] Heartbeat received from 88.99.249.217
2018-08-06 10:07:00,767 INFO [grpc-default-executor-38] n.d.k [PeerEventListener.java:162] Local blockchain @ 57979, 88.99.249.217 @ 68009
```

```
for reason: null
2018-08-06 10:20:42,666 WARN [grpc-default-executor-94] n.d.k [PeerEventListener.java:101] Rejected transaction for reason: null
2018-08-06 10:20:42,670 WARN [grpc-default-executor-90] n.d.k [PeerEventListener.java:101] Rejected transaction for reason: null
2018-08-06 10:20:42,676 WARN [grpc-default-executor-94] n.d.k [PeerEventListener.java:101] Rejected transaction for reason: null
2018-08-06 10:20:42,680 WARN [grpc-default-executor-92] n.d.k [PeerEventListener.java:101] Rejected transaction for reason: null
2018-08-06 10:20:42,685 WARN [grpc-default-executor-90] n.d.k [PeerEventListener.java:101] Rejected transaction for reason: null
2018-08-06 10:20:42,690 WARN [grpc-default-executor-94] n.d.k [PeerEventListener.java:101] Rejected transaction for reason: null
2018-08-06 10:20:42,695 WARN [grpc-default-executor-94] n.d.k [PeerEventListener.java:101] Rejected transaction for reason: null
2018-08-06 10:20:42,749 INFO [grpc-default-executor-92] n.d.b.c [SyncJob.java:244] Downloaded block 55205 from 35.237.197.48
2018-08-06 10:20:42,837 INFO [grpc-default-executor-92] n.d.b.c [SyncJob.java:244] Downloaded block 55206 from 35.237.197.48
2018-08-06 10:20:42,838 INFO [grpc-default-executor-92] n.d.b.c [SyncJob.java:244] Downloaded block 55207 from 35.237.197.48
2018-08-06 10:20:42,838 INFO [grpc-default-executor-92] n.d.b.c [SyncJob.java:244] Downloaded block 55208 from 35.237.197.48
2018-08-06 10:20:42,838 INFO [grpc-default-executor-92] n.d.b.c [SyncJob.java:244] Downloaded block 55209 from 35.237.197.48
2018-08-06 10:20:42,838 INFO [grpc-default-executor-92] n.d.b.c [SyncJob.java:244] Downloaded block 55210 from 35.237.197.48
2018-08-06 10:20:42,838 INFO [grpc-default-executor-92] n.d.b.c [SyncJob.java:244] Downloaded block 55211 from 35.237.197.48
2018-08-06 10:20:42,845 INFO [grpc-default-executor-92] n.d.b.c [SyncJob.java:244] Downloaded block 55212 from 35.237.197.48
2018-08-06 10:20:42,846 INFO [grpc-default-executor-92] n.d.b.c [SyncJob.java:244] Downloaded block 55213 from 35.237.197.48
2018-08-06 10:20:42,846 INFO [grpc-default-executor-92] n.d.b.c [SyncJob.java:244] Downloaded block 55214 from 35.237.197.48
2018-08-06 10:20:42,846 INFO [grpc-default-executor-92] n.d.b.c [SyncJob.java:244] Downloaded block 55215 from 35.237.197.48
2018-08-06 10:20:42,846 INFO [grpc-default-executor-92] n.d.b.c [SyncJob.java:244] Downloaded block 55216 from 35.237.197.48
2018-08-06 10:20:42,854 WARN [grpc-default-executor-92] n.d.k [PeerEventListener.java:101] Rejected transaction for reason: null
2018-08-06 10:20:42,854 INFO [grpc-default-executor-92] n.d.b.c [SyncJob.java:244] Downloaded block 55217 from 35.237.197.48
2018-08-06 10:20:42,854 INFO [grpc-default-executor-92] n.d.b.c [SyncJob.java:244] Downloaded block 55218 from 35.237.197.48
2018-08-06 10:20:42,854 INFO [grpc-default-executor-92] n.d.b.c [SyncJob.java:244] Downloaded block 55219 from 35.237.197.48
2018-08-06 10:20:42,855 INFO [grpc-default-executor-92] n.d.b.c [SyncJob.java:244] Downloaded block 55220 from 35.237.197.48
2018-08-06 10:20:42,855 INFO [grpc-default-executor-92] n.d.b.c [SyncJob.java:244] Downloaded block 55221 from 35.237.197.48
2018-08-06 10:20:42,863 INFO [grpc-default-executor-92] n.d.b.c [SyncJob.java:244] Downloaded block 55222 from 35.237.197.48
2018-08-06 10:20:42,880 INFO [grpc-default-executor-92] n.d.b.c [SyncJob.java:244] Downloaded block 55223 from 35.237.197.48
2018-08-06 10:20:42,880 INFO [grpc-default-executor-92] n.d.b.c [SyncJob.java:244] Downloaded block 55224 from 35.237.197.48
2018-08-06 10:20:42,880 INFO [grpc-default-executor-92] n.d.b.c [SyncJob.java:244] Downloaded block 55225 from 35.237.197.48
2018-08-06 10:20:42,888 INFO [grpc-default-executor-92] n.d.b.c [SyncJob.java:244] Downloaded block 55226 from 35.237.197.48
2018-08-06 10:20:42,888 INFO [grpc-default-executor-92] n.d.b.c [SyncJob.java:244] Downloaded block 55227 from 35.237.197.48
2018-08-06 10:20:42,888 INFO [grpc-default-executor-92] n.d.b.c [SyncJob.java:244] Downloaded block 55228 from 35.237.197.48
2018-08-06 10:20:42,889 INFO [grpc-default-executor-92] n.d.b.c [SyncJob.java:244] Downloaded block 55229 from 35.237.197.48
2018-08-06 10:20:43,027 WARN [grpc-default-executor-92] n.d.k [PeerEventListener.java:101] Rejected transaction for reason: null
2018-08-06 10:20:43,034 WARN [grpc-default-executor-90] n.d.k [PeerEventListener.java:101] Rejected transaction for reason: null
2018-08-06 10:20:43,040 WARN [grpc-default-executor-90] n.d.k [PeerEventListener.java:101] Rejected transaction for reason: null
2018-08-06 10:20:43,043 WARN [grpc-default-executor-94] n.d.k [PeerEventListener.java:101] Rejected transaction for reason: null
2018-08-06 10:20:43,046 WARN [grpc-default-executor-94] n.d.k [PeerEventListener.java:101] Rejected transaction for reason: null
2018-08-06 10:20:43,055 WARN [grpc-default-executor-90] n.d.k [PeerEventListener.java:101] Rejected transaction for reason: null
2018-08-06 10:20:43,131 WARN [grpc-default-executor-92] n.d.k [PeerEventListener.java:101] Rejected transaction for reason: null
2018-08-06 10:20:43,194 INFO [grpc-default-executor-92] n.d.b.c [SyncJob.java:244] Downloaded block 55230 from 35.237.197.48
2018-08-06 10:20:43,209 WARN [grpc-default-executor-92] n.d.k [PeerEventListener.java:101] Rejected transaction for reason: null
2018-08-06 10:20:43,441 INFO [grpc-default-executor-94] n.d.b.c [SyncJob.java:244] Downloaded block 55231 from 35.237.197.48
2018-08-06 10:20:43,457 WARN [grpc-default-executor-94] n.d.k [PeerEventListener.java:101] Rejected transaction for reason: null
2018-08-06 10:20:43,462 WARN [grpc-default-executor-94] n.d.k [PeerEventListener.java:101] Rejected transaction for reason: null
2018-08-06 10:20:43,467 WARN [grpc-default-executor-94] n.d.k [PeerEventListener.java:101] Rejected transaction for reason: null
2018-08-06 10:20:43,471 WARN [grpc-default-executor-94] n.d.k [PeerEventListener.java:101] Rejected transaction for reason: null
2018-08-06 10:20:43,476 WARN [grpc-default-executor-94] n.d.k [PeerEventListener.java:101] Rejected transaction for reason: null
2018-08-06 10:20:43,480 WARN [grpc-default-executor-94] n.d.k [PeerEventListener.java:101] Rejected transaction for reason: null
2018-08-06 10:20:43,484 WARN [grpc-default-executor-94] n.d.k [PeerEventListener.java:101] Rejected transaction for reason: null
2018-08-06 10:20:43,490 WARN [grpc-default-executor-92] n.d.k [PeerEventListener.java:101] Rejected transaction for reason: null
2018-08-06 10:20:43,493 WARN [grpc-default-executor-94] n.d.k [PeerEventListener.java:101] Rejected transaction for reason: null
2018-08-06 10:20:43,498 WARN [grpc-default-executor-92] n.d.k [PeerEventListener.java:101] Rejected transaction for reason: null
2018-08-06 10:20:43,501 WARN [grpc-default-executor-90] n.d.k [PeerEventListener.java:101] Rejected transaction for reason: null
2018-08-06 10:20:43,503 WARN [grpc-default-executor-94] n.d.k [PeerEventListener.java:101] Rejected transaction for reason: null
2018-08-06 10:20:43,507 WARN [grpc-default-executor-94] n.d.k [PeerEventListener.java:101] Rejected transaction for reason: null
2018-08-06 10:20:43,511 WARN [grpc-default-executor-90] n.d.k [PeerEventListener.java:101] Rejected transaction for reason: null
2018-08-06 10:20:43,516 WARN [grpc-default-executor-84] n.d.k [PeerEventListener.java:101] Rejected transaction for reason: null
2018-08-06 10:20:43,518 WARN [grpc-default-executor-88] n.d.k [PeerEventListener.java:101] Rejected transaction for reason: null
2018-08-06 10:20:43,520 WARN [grpc-default-executor-88] n.d.k [PeerEventListener.java:101] Rejected transaction for reason: null
2018-08-06 10:20:43,523 WARN [grpc-default-executor-92] n.d.k [PeerEventListener.java:101] Rejected transaction for reason: null
2018-08-06 10:20:43,528 WARN [grpc-default-executor-84] n.d.k [PeerEventListener.java:101] Rejected transaction for reason: null
2018-08-06 10:20:43,530 WARN [grpc-default-executor-88] n.d.k [PeerEventListener.java:101] Rejected transaction for reason: null
2018-08-06 10:20:43,535 WARN [grpc-default-executor-84] n.d.k [PeerEventListener.java:101] Rejected transaction for reason: null
2018-08-06 10:20:43,538 WARN [grpc-default-executor-92] n.d.k [PeerEventListener.java:101] Rejected transaction for reason: null
2018-08-06 10:20:43,542 WARN [grpc-default-executor-90] n.d.k [PeerEventListener.java:101] Rejected transaction for reason: null
2018-08-06 10:20:43,546 WARN [grpc-default-executor-88] n.d.k [PeerEventListener.java:101] Rejected transaction for reason: null
2018-08-06 10:20:43,550 WARN [grpc-default-executor-92] n.d.k [PeerEventListener.java:101] Rejected transaction for reason: null
2018-08-06 10:20:43,554 WARN [grpc-default-executor-90] n.d.k [PeerEventListener.java:101] Rejected transaction for reason: null
2018-08-06 10:20:43,558 WARN [grpc-default-executor-84] n.d.k [PeerEventListener.java:101] Rejected transaction for reason: null
2018-08-06 10:20:43,562 WARN [grpc-default-executor-84] n.d.k [PeerEventListener.java:101] Rejected transaction for reason: null
2018-08-06 10:20:43,567 WARN [grpc-default-executor-92] n.d.k [PeerEventListener.java:101] Rejected transaction for reason: null
2018-08-06 10:20:43,638 WARN [grpc-default-executor-92] n.d.k [PeerEventListener.java:101] Rejected transaction for reason: null
2018-08-06 10:20:43,641 WARN [grpc-default-executor-92] n.d.k [PeerEventListener.java:101] Rejected transaction for reason: null
2018-08-06 10:20:43,646 WARN [grpc-default-executor-84] n.d.k [PeerEventListener.java:101] Rejected transaction for reason: null
2018-08-06 10:20:43,649 WARN [grpc-default-executor-92] n.d.k [PeerEventListener.java:101] Rejected transaction for reason: null
2018-08-06 10:20:43,658 WARN [grpc-default-executor-88] n.d.k [PeerEventListener.java:101] Rejected transaction for reason: null
2018-08-06 10:20:43,670 WARN [grpc-default-executor-84] n.d.k [PeerEventListener.java:101] Rejected transaction for reason: null
2018-08-06 10:20:43,677 WARN [grpc-default-executor-92] n.d.k [PeerEventListener.java:101] Rejected transaction for reason: null
2018-08-06 10:20:43,682 WARN [grpc-default-executor-90] n.d.k [PeerEventListener.java:101] Rejected transaction for reason: null
2018-08-06 10:20:43,698 WARN [grpc-default-executor-90] n.d.k [PeerEventListener.java:101] Rejected transaction for reason: null
2018-08-06 10:20:43,717 WARN [grpc-default-executor-90] n.d.k [PeerEventListener.java:101] Rejected transaction for reason: null
2018-08-06 10:20:43,725 WARN [grpc-default-executor-84] n.d.k [PeerEventListener.java:101] Rejected transaction for reason: null
2018-08-06 10:20:43,733 WARN [grpc-default-executor-84] n.d.k [PeerEventListener.java:101] Rejected transaction for reason: null
2018-08-06 10:20:43,740 WARN [grpc-default-executor-84] n.d.k [PeerEventListener.java:101] Rejected transaction for reason: null
2018-08-06 10:20:43,882 INFO [grpc-default-executor-92] n.d.b.c [SyncJob.java:244] Downloaded block 55232 from 35.237.197.48
2018-08-06 10:20:44,003 WARN [grpc-default-executor-92] n.d.k [PeerEventListener.java:101] Rejected transaction for reason: null
2018-08-06 10:20:44,007 WARN [grpc-default-executor-88] n.d.k [PeerEventListener.java:101] Rejected transaction for reason: null
2018-08-06 10:20:44,012 WARN [grpc-default-executor-90] n.d.k [PeerEventListener.java:101] Rejected transaction for reason: null
2018-08-06 10:20:44,017 WARN [grpc-default-executor-92] n.d.k [PeerEventListener.java:101] Rejected transaction for reason: null
2018-08-06 10:20:44,021 WARN [grpc-default-executor-84] n.d.k [PeerEventListener.java:101] Rejected transaction for reason: null
2018-08-06 10:20:44,026 WARN [grpc-default-executor-90] n.d.k [PeerEventListener.java:101] Rejected transaction for reason: null
2018-08-06 10:20:44,030 WARN [grpc-default-executor-92] n.d.k [PeerEventListener.java:101] Rejected transaction for reason: null
2018-08-06 10:20:44,033 WARN [grpc-default-executor-88] n.d.k [PeerEventListener.java:101] Rejected transaction for reason: null
2018-08-06 10:20:44,036 WARN [grpc-default-executor-88] n.d.k [PeerEventListener.java:101] Rejected transaction for reason: null
2018-08-06 10:20:44,039 WARN [grpc-default-executor-88] n.d.k [PeerEventListener.java:101] Rejected transaction for reason: null
2018-08-06 10:20:44,042 WARN [grpc-default-executor-88] n.d.k [PeerEventListener.java:101] Rejected transaction for reason: null
2018-08-06 10:20:44,045 WARN [grpc-default-executor-88] n.d.k [PeerEventListener.java:101] Rejected transaction for reason: null
2018-08-06 10:20:44,048 WARN [grpc-default-executor-88] n.d.k [PeerEventListener.java:101] Rejected transaction for reason: null
2018-08-06 10:20:44,079 WARN [grpc-default-executor-84] n.d.k [PeerEventListener.java:101] Rejected transaction for reason: null
2018-08-06 10:20:44,086 WARN [grpc-default-executor-92] n.d.k [PeerEventListener.java:101] Rejected transaction for reason: null
2018-08-06 10:20:44,174 WARN [grpc-default-executor-92] n.d.k [PeerEventListener.java:101] Rejected transaction for reason: null
2018-08-06 10:20:44,189 WARN [grpc-default-executor-92] n.d.k [PeerEventListener.java:101] Rejected transaction for reason: null
2018-08-06 10:20:44,278 INFO [grpc-default-executor-84] n.d.b.c [SyncJob.java:244] Downloaded block 55233 from 35.237.197.48
2018-08-06 10:20:44,460 WARN [grpc-default-executor-84] n.d.k [PeerEventListener.java:101] Rejected transaction for reason: null
2018-08-06 10:20:44,463 WARN [grpc-default-executor-88] n.d.k [PeerEventListener.java:101] Rejected transaction for reason: null
2018-08-06 10:20:44,466 WARN [grpc-default-executor-88] n.d.k [PeerEventListener.java:101] Rejected transaction for reason: null
2018-08-06 10:20:44,469 WARN [grpc-default-executor-88] n.d.k [PeerEventListener.java:101] Rejected transaction for reason: null
2018-08-06 10:20:44,567 INFO [grpc-default-executor-84] n.d.b.c [SyncJob.java:244] Downloaded block 55234 from 35.237.197.48
2018-08-06 10:20:44,614 WARN [grpc-default-executor-84] n.d.k [PeerEventListener.java:101] Rejected transaction for reason: null
2018-08-06 10:20:44,619 WARN [grpc-default-executor-90] n.d.k [PeerEventListener.java:101] Rejected transaction for reason: null
2018-08-06 10:20:44,624 WARN [grpc-default-executor-84] n.d.k [PeerEventListener.java:101] Rejected transaction for reason: null
2018-08-06 10:20:44,818 WARN [grpc-default-executor-90] n.d.k [PeerEventListener.java:382] Event stream error from 35.237.197.48: Status{code=CANCELLED, description=Failed to read message., cause=io.grpc.StatusRuntimeException: INTERNAL: Invalid protobuf byte sequence
	at io.grpc.Status.asRuntimeException(Status.java:517)
	at io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller.parse(ProtoLiteUtils.java:218)
	at io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller.parse(ProtoLiteUtils.java:118)
	at io.grpc.MethodDescriptor.parseResponse(MethodDescriptor.java:266)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1MessagesAvailable.runInContext(ClientCallImpl.java:519)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.google.protobuf.InvalidProtocolBufferException: Protocol message had invalid UTF-8.
	at com.google.protobuf.InvalidProtocolBufferException.invalidUtf8(InvalidProtocolBufferException.java:148)
	at com.google.protobuf.CodedInputStream$ArrayDecoder.readStringRequireUtf8(CodedInputStream.java:830)
	at nodecore.api.grpc.VeriBlockMessages$Transaction.<init>(VeriBlockMessages.java:12993)
	at nodecore.api.grpc.VeriBlockMessages$Transaction.<init>(VeriBlockMessages.java:12885)
	at nodecore.api.grpc.VeriBlockMessages$Transaction$1.parsePartialFrom(VeriBlockMessages.java:14962)
	at nodecore.api.grpc.VeriBlockMessages$Transaction$1.parsePartialFrom(VeriBlockMessages.java:14957)
	at com.google.protobuf.CodedInputStream$ArrayDecoder.readMessage(CodedInputStream.java:911)
	at nodecore.api.grpc.VeriBlockMessages$SignedTransaction.<init>(VeriBlockMessages.java:2536)
	at nodecore.api.grpc.VeriBlockMessages$SignedTransaction.<init>(VeriBlockMessages.java:2477)
	at nodecore.api.grpc.VeriBlockMessages$SignedTransaction$1.parsePartialFrom(VeriBlockMessages.java:3179)
	at nodecore.api.grpc.VeriBlockMessages$SignedTransaction$1.parsePartialFrom(VeriBlockMessages.java:3174)
	at com.google.protobuf.CodedInputStream$ArrayDecoder.readMessage(CodedInputStream.java:911)
	at nodecore.api.grpc.VeriBlockMessages$TransactionUnion.<init>(VeriBlockMessages.java:15073)
	at nodecore.api.grpc.VeriBlockMessages$TransactionUnion.<init>(VeriBlockMessages.java:15017)
	at nodecore.api.grpc.VeriBlockMessages$TransactionUnion$1.parsePartialFrom(VeriBlockMessages.java:16001)
	at nodecore.api.grpc.VeriBlockMessages$TransactionUnion$1.parsePartialFrom(VeriBlockMessages.java:15996)
	at com.google.protobuf.CodedInputStream$ArrayDecoder.readMessage(CodedInputStream.java:911)
	at nodecore.api.grpc.VeriBlockMessages$Block.<init>(VeriBlockMessages.java:27186)
	at nodecore.api.grpc.VeriBlockMessages$Block.<init>(VeriBlockMessages.java:27078)
	at nodecore.api.grpc.VeriBlockMessages$Block$1.parsePartialFrom(VeriBlockMessages.java:29261)
	at nodecore.api.grpc.VeriBlockMessages$Block$1.parsePartialFrom(VeriBlockMessages.java:29256)
	at com.google.protobuf.CodedInputStream$ArrayDecoder.readMessage(CodedInputStream.java:911)
	at nodecore.api.grpc.VeriBlockMessages$Event.<init>(VeriBlockMessages.java:46636)
	at nodecore.api.grpc.VeriBlockMessages$Event.<init>(VeriBlockMessages.java:46592)
	at nodecore.api.grpc.VeriBlockMessages$Event$1.parsePartialFrom(VeriBlockMessages.java:49106)
	at nodecore.api.grpc.VeriBlockMessages$Event$1.parsePartialFrom(VeriBlockMessages.java:49101)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:91)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:49)
	at io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller.parseFrom(ProtoLiteUtils.java:223)
	at io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller.parse(ProtoLiteUtils.java:215)
	... 8 more
}
2018-08-06 10:20:44,819 INFO [grpc-default-executor-90] n.d.b.c [SyncJob.java:187] Aborting sync with peer 35.237.197.48
2018-08-06 10:20:44,819 INFO [grpc-default-executor-90] n.d.b.c [SyncJob.java:195] Job bf394aaa-1e5a-49d4-a604-75054fe7df97 has been canceled.
2018-08-06 10:20:44,819 INFO [grpc-default-executor-90] nodecore.h [NodeCoreState.java:76] NodeCore blockchain state is now: Stale
2018-08-06 10:20:44,819 INFO [grpc-default-executor-90] n.d.c [DefaultPeerHub.java:223] Job bf394aaa-1e5a-49d4-a604-75054fe7df97 completed, there are now 0 reconcile/sync jobs running
2018-08-06 10:20:44,821 ERROR [pool-56-thread-1] n.d.b.c [SyncJob.java:142] null
java.lang.InterruptedException: null
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedNanos(AbstractQueuedSynchronizer.java:1039)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1328)
	at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:277)
	at nodecore.d.b.c.g(SyncJob.java:129)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2018-08-06 10:20:45,010 WARN [grpc-default-executor-90] n.d.k [PeerEventListener.java:101] Rejected transaction for reason: null
2018-08-06 10:20:45,015 WARN [grpc-default-executor-90] n.d.k [PeerEventListener.java:101] Rejected transaction for reason: null
2018-08-06 10:20:45,020 WARN [grpc-default-executor-90] n.d.k [PeerEventListener.java:101] Rejected transaction for reason: null
2018-08-06 10:20:45,023 WARN [grpc-default-executor-84] n.d.k [PeerEventListener.java:101] Rejected transaction for reason: null
2018-08-06 10:20:45,026 WARN [grpc-default-executor-84] n.d.k [PeerEventListener.java:101] Rejected transaction for reason: null
```

**Comment by JoshRack** [comment]
This code has all been replaced.
